"""IT question banks + lessons: Python learning path."""
from __future__ import annotations

IT_BANKS: dict[str, list[tuple]] = {
    "python-basics": [
        ("What does print(3 * 2 + 1) output?", ["6", "7", "9", "5"], 1, "Multiplication binds tighter than addition, so 3 * 2 = 6 first and then 6 + 1 = 7."),
        ("What is the type of 5 / 2?", ["int", "str", "float", "complex"], 2, "The true-division operator / always returns a float, even when the result is a whole number."),
        ("What does print(2 ** 3 ** 2) output?", ["512", "64", "36", "81"], 0, "The ** operator is right-associative, so it evaluates as 2 ** (3 ** 2) = 2 ** 9 = 512."),
        ("What does print(-7 // 2, -7 % 2) output?", ["-4 1", "-3 1", "-3.5 0.5", "-4 -1"], 0, "Floor division rounds toward negative infinity giving -4, and % takes the divisor's sign so the remainder is 1."),
        ("Which expression evaluates to False?", ["bool('False')", "bool([0])", "bool(0.0)", "bool(' ')"], 2, "0.0 is falsy, while every other option is a non-empty string or list, which are truthy."),
        ("What does print(type(True + True)) output?", ["<class 'bool'>", "TypeError", "<class 'int'>", "<class 'float'>"], 2, "bool is a subclass of int, so the addition is integer arithmetic and the result type is int."),
        ("What does print(0.1 + 0.2 == 0.3) output?", ["True", "False", "0.3", "raises TypeError"], 1, "Binary floats cannot represent 0.1 or 0.2 exactly, so the sum is 0.30000000000000004, not 0.3."),
        ("What does print(int('42') + float('3')) output?", ["'423'", "45", "45.0", "TypeError"], 2, "The operands become 42 and 3.0, and mixing int with float promotes the result to the float 45.0."),
        ("What does print(divmod(7, 3)) output?", ["(2, 1)", "(2, 0)", "(3, 1)", "(2, 3)"], 0, "divmod returns a (quotient, remainder) tuple: 7 // 3 is 2 and 7 % 3 is 1."),
        ("What does print('py' 'thon') output?", ["'py' 'thon'", "py thon", "SyntaxError", "python"], 3, "Adjacent string literals are merged at parse time, so the expression evaluates to one string, 'python'."),
        ("Which of these objects is immutable?", ["[1, 2]", "{'a': 1}", "(1, 2)", "{1, 2}"], 2, "Tuples are immutable sequences, while lists, dicts and sets can all be modified in place."),
        ("What does print('hello'[1:3]) output?", ["he", "el", "llo", "lo"], 1, "Slices are half-open: index 1 is included and index 3 is excluded, leaving the two characters 'el'."),
    ],
    "python-variables": [
        ("What does this code print?\nx = [1, 2]\ny = x\ny.append(3)\nprint(x)", ["[1, 2]", "[1, 2, 3]", "[3]", "TypeError"], 1, "Assignment binds y to the same list object as x, so mutating through y is also visible through x."),
        ("What happens when this runs?\na = (1, 2)\na[0] = 9", ["a becomes (9, 2)", "TypeError: 'tuple' object does not support item assignment", "a becomes [9, 2]", "IndexError: index out of range"], 1, "Tuples are immutable sequences, so item assignment raises TypeError instead of changing the value."),
        ("What does print(type(x)) show after x = 5 and then x = 'text'?", ["<class 'int'>", "<class 'str'>", "<class 'object'>", "TypeError: reassignment"], 1, "Names are labels bound to objects and Python is dynamically typed, so x can be rebound to a string."),
        ("What does this print?\nx, y = 1, 2\nx, y = y, x\nprint(x, y)", ["1 2", "2 1", "2 2", "NameError"], 1, "The right side packs (y, x) into a tuple and immediately unpacks it, swapping both names in one statement."),
        ("Given a = 256 and b = 256.0, what does print(a is b) output?", ["True", "False", "TypeError", "256"], 1, "a is an int object and b is a float object, so they are distinct objects even though a == b is True."),
        ("What does this print?\nd = {'a': 1}\ne = d\ne['b'] = 2\nprint(len(d))", ["1", "2", "3", "KeyError"], 1, "e and d reference the same dict, so adding a key through e also changes d, giving two keys."),
        ("Which is NOT a valid Python variable name?", ["_temp", "2fast", "my_var", "MAX_SIZE"], 1, "Identifiers may not begin with a digit; the other three all follow Python's identifier rules."),
        ("What does this print?\na = b = [0]\na = [1]\nprint(b)", ["[1]", "[0]", "[0, 1]", "NameError"], 1, "Rebinding a to a brand-new list leaves the original list untouched, and b still points at that original list."),
        ("What does this print?\na = [[1], [2]]\nb = a.copy()\nb[0].append(9)\nprint(a)", ["[[1], [2]]", "[[1, 9], [2]]", "[[1], [2], [9]]", "TypeError"], 1, "copy() is shallow, so b holds a new outer list whose cells still point at the same inner lists a sees."),
        ("What does this print?\ns = 'ab'\nt = s\nt += 'c'\nprint(s)", ["'abc'", "'ab' 'abc'", "'ab'", "TypeError"], 2, "Strings are immutable, so += builds a new string and rebinds t, leaving s pointing at the original 'ab'."),
        ("What happens?\ndef f(x: int) -> str:\n    return x\nprint(f('text'))", ["TypeError", "ValueError", "Returns 5", "Returns 'text' with no error"], 3, "Annotations are documentation only and are not enforced at runtime, so the function returns the string it was given."),
        ("What does this print?\nx = 5\ndel x\nprint(x)", ["NameError: name 'x' is not defined", "None", "0", "5"], 0, "del removes the binding entirely, so the later read finds no name and raises NameError."),
    ],
    "python-loops": [
        ("What does print(list(range(1, 10, 3))) output?", ["[1, 4, 7]", "[1, 3, 6, 9]", "[3, 6, 9]", "[1, 4, 7, 10]"], 0, "range(1, 10, 3) yields 1, 4 and 7, then stops because the next value would reach or pass 10."),
        ("What does this print?\ntotal = 0\nfor i in range(5):\n    if i == 3:\n        break\n    total += i\nprint(total)", ["6", "3", "10", "0"], 1, "The loop adds 0 + 1 + 2 and stops as soon as i equals 3, so total stays 3."),
        ("What does this print?\nfor i in range(3):\n    if i == 5:\n        break\nelse:\n    print('done')", ["done", "nothing", "0 1 2", "SyntaxError"], 0, "A loop's else clause runs only when the loop finishes without break, and i never reaches 5."),
        ("What does this print?\nn = 0\nfor i in range(3):\n    for j in range(3):\n        if j == 1:\n            continue\n        n += 1\nprint(n)", ["3", "6", "9", "4"], 1, "continue only skips the inner loop's iteration, so j = 1 is skipped for each of the three i values, giving 6."),
        ("What is len(range(2, 10, 3))?", ["2", "3", "4", "raises ValueError"], 1, "The range covers 2, 5 and 8 before passing 10, so it contains exactly three values."),
        ("What does print(list(enumerate('ab', start=1))) output?", ["[(1, 'a'), (2, 'b')]", "['a', 'b']", "[(0, 'a'), (1, 'b')]", "[(1, 2)]"], 0, "enumerate with start=1 pairs each character with a counter that begins at 1 instead of 0."),
        ("What does this print?\ni = 10\nwhile i > 7:\n    i -= 1\nprint(i)", ["7", "8", "10", "infinite loop"], 0, "The loop decrements while i > 7, so it exits with i exactly equal to 7."),
        ("What does print(list({'a': 1, 'b': 2})) output?", ["['a', 'b']", "[1, 2]", "[('a', 1), ('b', 2)]", "['a', 1, 'b', 2]"], 0, "Iterating over a dict yields its keys in insertion order, so list(d) returns only the keys."),
        ("What does print(list(zip([1, 2, 3], 'ab'))) output?", ["[(1, 'a'), (2, 'b')]", "[(1, 'a'), (2, 'b'), (3, None)]", "ValueError: lengths differ", "[(1, 2), (3, 'a')]"], 0, "zip stops as soon as one iterable is exhausted, so the extra 3 is dropped instead of raising an error."),
        ("What does this print?\nfor i in range(3):\n    pass\nprint(i)", ["NameError", "0 1 2", "2", "3"], 2, "The loop variable is not scoped to the loop, so after the last iteration it still holds the value 2."),
        ("What does this print?\nnums = [1, 2, 3]\nfor n in nums:\n    nums.remove(n)\nprint(nums)", ["[]", "[2]", "[1, 3]", "infinite loop"], 1, "The list iterator tracks positions, so removals shift later items left and skip them, leaving only the never-visited 2."),
        ("What does print([x for x in range(10) if x % 3 == 0]) output?", ["[3, 6, 9]", "[0, 3, 6]", "[0, 3, 6, 9, 10]", "[0, 3, 6, 9]"], 3, "range(10) includes 0, and the multiples of 3 below 10 are 0, 3, 6 and 9."),
    ],
    "python-functions": [
        ("What does this print?\ndef f(lst=[]):\n    lst.append(1)\n    return lst\nprint(f(), f())", ["[1] [1]", "[1] [1, 1]", "[1, 1] [1, 1]", "[] [1]"], 1, "The default list is created once at definition time and shared, so the first call mutates the list the second call reuses."),
        ("What happens?\nx = 1\ndef f():\n    x = x + 1\nf()", ["Prints 2", "UnboundLocalError", "NameError", "Modifies the global x"], 1, "Assigning to x anywhere in the function makes it local, so reading it before assignment raises UnboundLocalError."),
        ("What does this print?\ndef f():\n    print('hi')\nprint(f())", ["hi", "hi then None", "None", "hi then ''"], 1, "The function prints hi and, having no return statement, returns None, which print then displays."),
        ("What does this print?\ndef f(*args, **kwargs):\n    return len(args) + len(kwargs)\nprint(f(1, 2, a=3, b=4))", ["2", "3", "4", "5"], 2, "args captures (1, 2) and kwargs captures two entries, so the lengths add up to 4."),
        ("What does print(sorted([3, 1, 2], key=lambda x: -x)) output?", ["[1, 2, 3]", "[3, 2, 1]", "[2, 3, 1]", "[-3, -2, -1]"], 1, "Sorting by the negated value reverses the natural order, producing a descending list of the original numbers."),
        ("What does print(list(map(lambda x: x * 2, filter(lambda x: x % 2, [1, 2, 3, 4])))) output?", ["[1, 3]", "[2, 4]", "[2, 6]", "[1, 2, 3, 4]"], 2, "filter keeps the odd values 1 and 3, then map doubles them to 2 and 6."),
        ("What does this print?\ndef deco(fn):\n    def wrapper(*a):\n        return fn(*a) + 1\n    return wrapper\n@deco\ndef add(a, b):\n    return a + b\nprint(add(2, 3))", ["5", "6", "10", "TypeError"], 1, "The decorator replaces add with wrapper, so the call returns (2 + 3) + 1 = 6."),
        ("What does this print?\ncount = 0\ndef inc():\n    global count\n    count += 1\ninc()\ninc()\nprint(count)", ["0", "1", "2", "UnboundLocalError"], 2, "Declaring count global lets the function update the module-level variable, so after two calls it is 2."),
        ("What does this print?\ndef counter():\n    n = 0\n    def inc():\n        nonlocal n\n        n += 1\n        return n\n    return inc\nc = counter()\nc()\nprint(c())", ["1", "2", "0", "UnboundLocalError"], 1, "nonlocal binds n to the enclosing function's variable, so both calls share one counter and the second returns 2."),
        ("What does this print?\ndef gen():\n    yield 1\n    yield 2\nprint(list(gen()))", ["[1, 2]", "[1]", "1 2", "None"], 0, "Calling gen() creates a generator that yields 1 then 2, and list() drains it into [1, 2]."),
        ("What does this print?\ndef f(a, *, b=2):\n    return a + b\nprint(f(1, b=3))", ["1 3", "3", "TypeError", "4"], 3, "The bare * makes b keyword-only, and with a=1 and b=3 the function returns 4."),
        ("What does this print?\ndef apply_twice(fn, x):\n    return fn(fn(x))\nprint(apply_twice(lambda v: v * 2, 3))", ["6", "9", "12", "TypeError"], 2, "Functions are first-class objects, so the lambda runs twice: 3 becomes 6, then 6 becomes 12."),
    ],
    "python-oop": [
        ("What does this print?\nclass A: pass\nclass B(A): pass\nclass C(A): pass\nclass D(B, C): pass\nprint([c.__name__ for c in D.__mro__])", ["['D', 'B', 'C', 'A', 'object']", "['D', 'A', 'B', 'C', 'object']", "['D', 'B', 'A', 'C', 'object']", "['A', 'B', 'C', 'D', 'object']"], 0, "C3 linearisation keeps B before C and leaves the shared base A after both, giving D, B, C, A, object."),
        ("What does this print?\nclass C:\n    count = 0\n    def __init__(self):\n        C.count += 1\na = C()\nb = C()\nprint(C.count)", ["0", "1", "2", "4"], 2, "count is a class attribute shared by every instance, so constructing two objects increments it to 2."),
        ("What does print(isinstance(True, int)) output?", ["True", "False", "TypeError", "<class 'bool'>"], 0, "bool is a subclass of int in Python, so True passes an isinstance check against int."),
        ("What does this print?\nclass C:\n    def __init__(self):\n        self.__x = 1\nc = C()\nprint(c._C__x)", ["1", "AttributeError", "None", "<class 'int'>"], 0, "Name mangling rewrites self.__x into self._C__x, so the attribute is reachable under the mangled name."),
        ("What does this print?\nclass A:\n    def __init__(self):\n        self.v = 1\nclass B(A):\n    def __init__(self):\n        self.w = 2\nb = B()\nprint(b.v)", ["1", "2", "AttributeError", "None"], 2, "B.__init__ overrides A's version and never calls super().__init__(), so self.v is never created."),
        ("What does this print?\nclass C:\n    x = 1\nc1 = C()\nc2 = C()\nc1.x = 5\nprint(c2.x)", ["5", "1", "TypeError", "0"], 1, "Assigning c1.x creates an instance attribute that shadows the class attribute for c1 only, so c2 still reads 1."),
        ("What does this print?\nclass C:\n    @property\n    def val(self):\n        return 42\nprint(C().val)", ["42", "<property object at ...>", "None", "TypeError"], 0, "@property turns val into a managed attribute, so accessing it without parentheses runs the getter and returns 42."),
        ("What does this print?\nclass Dog:\n    def __init__(self, name):\n        self.name = name\n    def speak(self):\n        return self.name + ' says woof'\nprint(Dog('Rex').speak())", ["Rex says woof", "self says woof", "says woof", "NameError"], 0, "The method is bound to the instance, so self is passed automatically and self.name resolves to 'Rex'."),
        ("What does this print?\nclass C:\n    def __str__(self):\n        return 'S'\n    def __repr__(self):\n        return 'R'\nprint(str(C()))", ["R", "S", "<C object>", "TypeError"], 1, "str() uses __str__ when the class defines it and falls back to __repr__ only when it does not."),
        ("What does this print?\nclass A:\n    def m(self):\n        return 'A'\nclass B(A):\n    def m(self):\n        return super().m() + 'B'\nprint(B().m())", ["AB", "BA", "B", "AttributeError"], 0, "super() resumes the search after B in the MRO, so A.m() runs first and the result concatenates to 'AB'."),
        ("What does this print?\nclass C:\n    def __init__(self, v):\n        self.v = v\n    def __eq__(self, other):\n        return self.v == other.v\nprint(len({C(1), C(1)}))", ["1", "2", "TypeError", "raises ValueError"], 2, "Defining __eq__ without __hash__ sets __hash__ to None, so instances are unhashable and the set literal raises TypeError."),
        ("What happens if __init__ returns a non-None value?", ["The object becomes that value", "The value is stored on the instance", "The instance is never created", "TypeError: __init__() should return None"], 3, "__init__ must return None; returning anything else raises TypeError because instance creation is handled by __new__."),
    ],
    "python-file-handling": [
        ("f.txt already contains 'old'. What does this print?\nwith open('f.txt', 'w') as fh:\n    fh.write('new')\nwith open('f.txt') as fh:\n    print(fh.read())", ["old", "oldnew", "new", "newold"], 2, "Mode 'w' truncates the file before writing, so the previous contents are replaced entirely by 'new'."),
        ("Which file mode raises FileNotFoundError when the file does not exist?", ["'w'", "'a'", "'r'", "'x'"], 2, "Mode 'r' can only open an existing file, while 'w' and 'x' create and 'a' creates the file if it is missing."),
        ("What does fh.write('abc') return when the file is opened in text mode?", ["None", "3", "'abc'", "True"], 1, "Text-mode write returns the number of characters written, which here is 3."),
        ("Which call reads and parses JSON from an open file object?", ["json.loads(fh)", "json.load(fh)", "json.dump(fh)", "json.read(fh)"], 1, "json.load takes a file-like object, whereas json.loads takes a str or bytes object."),
        ("What does open('data.bin', 'ab') expect fh.write to receive?", ["str", "bytes", "int", "any picklable object"], 1, "Binary mode indicated by 'b' writes bytes; passing a str in binary mode raises TypeError."),
        ("Which statement guarantees the file is closed even if an exception occurs in the block?", ["fh.flush()", "The with statement", "Assigning None to fh", "fh.seek(0)"], 1, "The with statement closes the file through the context manager's __exit__, which runs even when an exception is raised."),
        ("What does fh.readlines() return?", ["One string with the entire file", "A list of lines each still ending in its newline", "A list of lines with newlines stripped", "A generator of stripped lines"], 1, "readlines returns a list and preserves each line's trailing newline character."),
        ("What does this print?\nwith open('f.txt', 'w') as fh:\n    fh.write('a')\n    fh.write('b')\nwith open('f.txt') as fh:\n    print(fh.readlines())", ["['ab']", "['a', 'b']", "['a\\n', 'b\\n']", "['ab\\n']"], 0, "Neither write adds a newline, so both characters land on one line and readlines yields the single element 'ab'."),
        ("Why pass encoding='utf-8' to open() instead of relying on the default?", ["It opens the file in binary mode", "It makes decoding independent of the machine's locale", "It creates the file when missing", "It speeds up reading"], 1, "Without an explicit encoding, open() uses the platform default, so the same bytes can decode differently on another machine."),
        ("Which call turns a Python dict into a JSON string without touching a file?", ["json.load(d)", "json.decode(d)", "json.dumps(d)", "json.dump(d)"], 2, "json.dumps returns a str, while json.dump writes to a file object and json.load reads from one."),
        ("What does Path('a/b.txt').suffix return?", ["'.txt'", "'b.txt'", "'txt'", "'a/b.txt'"], 0, "suffix includes the leading dot and returns only the final extension of the file name."),
        ("What happens if you call fh.write('x') on a file opened with open('f.txt', 'r')?", ["The text is appended", "The file is truncated", "Nothing happens", "io.UnsupportedOperation: not writable"], 3, "A handle opened for reading has no write capability, so attempting to write raises io.UnsupportedOperation."),
    ],
    "python-apis": [
        ("How do you send query parameters with the requests library?", ["requests.get(url, params={'q': 'py'})", "requests.get(url, query={'q': 'py'})", "requests.get(url, body={'q': 'py'})", "requests.get(url + {'q': 'py'})"], 0, "requests serialises the params dict into the query string; data would send a body and you cannot add a dict to a str."),
        ("What does response.json() return?", ["The raw response body as str", "A Python object parsed from the JSON body", "The request URL", "A JSON-encoded str"], 1, "json() decodes the body using json.loads and returns a dict, list, or scalar value."),
        ("Which HTTP status code signals that a resource was created?", ["200", "201", "204", "301"], 1, "201 Created is the standard status returned after successfully creating a resource."),
        ("Which library supports both synchronous and asynchronous HTTP requests?", ["requests", "httpx", "urllib.parse", "json"], 1, "httpx offers a requests-like API plus AsyncClient, while the requests library is synchronous only."),
        ("What does response.raise_for_status() do?", ["Prints the status code", "Raises an HTTPError for 4xx and 5xx responses", "Retries the request automatically", "Returns a boolean"], 1, "It raises requests.exceptions.HTTPError for client and server errors and stays silent for 2xx and 3xx responses."),
        ("Which HTTP method is intended for partial updates in a REST API?", ["GET", "POST", "PATCH", "DELETE"], 2, "PATCH updates only the fields supplied, whereas PUT is intended to replace the entire resource."),
        ("Where should an API token normally be attached to a request?", ["In an Authorization header", "In the URL fragment", "In the Accept header", "Only as a query parameter"], 0, "The Authorization: Bearer header keeps credentials out of URLs, browser history and server access logs."),
        ("Which header declares that the request body is JSON?", ["Accept: application/json", "Content-Type: application/json", "Authorization: application/json", "X-Body: json"], 1, "Content-Type describes the format of the body being sent, while Accept asks for a response format."),
        ("Which status code means the server processed the request successfully but returns no body?", ["200", "204", "304", "404"], 1, "204 No Content signals success with an empty response body, whereas 200 normally carries content."),
        ("What Content-Type header does requests.post(url, json={'a': 1}) send?", ["application/json", "It sends no Content-Type header", "application/x-www-form-urlencoded", "text/plain"], 0, "The json= argument serialises the payload and sets Content-Type: application/json automatically."),
        ("What happens when requests.get(url, timeout=3) gets no response within 3 seconds?", ["The call blocks until the server replies", "The request is retried automatically", "A 408 response is returned", "requests raises requests.exceptions.Timeout"], 3, "The timeout caps how long requests will wait, raising Timeout (ConnectTimeout and ReadTimeout subclass it) instead of hanging."),
        ("How do the 401 and 403 status codes differ?", ["403 means credentials are invalid; 401 means not allowed", "They mean the same thing", "401 means credentials are missing or invalid; 403 means the request is understood but refused", "401 is only returned by FastAPI"], 2, "401 reports missing or bad credentials and asks the client to authenticate, while 403 refuses an authenticated client that lacks permission."),
    ],
    "python-fastapi": [
        ("Given @app.get('/items/{item_id}') with def read(item_id: int), what does GET /items/abc return?", ["{'item_id': 'abc'}", "404 Not Found", "422 validation error", "500 Server Error"], 2, "FastAPI converts and validates path parameters, so a value that is not an integer fails validation with 422."),
        ("What does @app.post('/users', status_code=201) do on success?", ["Returns 201 instead of the default 200", "Returns 200", "Sends no response body", "Raises an exception"], 0, "FastAPI uses status_code to set the success status, overriding the default 200 for POST routes."),
        ("Which mechanism runs shared logic such as auth checks before a route executes?", ["The Depends function in the signature", "Only a global middleware", "@app.before_request", "Manual calls inside every route"], 0, "Dependencies declared with Depends(...) are resolved automatically and their results are injected into the route."),
        ("What happens if a Pydantic request body model fails validation?", ["The route runs with default values", "422 Unprocessable Entity with error details", "400 Bad Request", "The server crashes"], 1, "FastAPI returns 422 along with a JSON body listing the error for each invalid field."),
        ("Why must @app.get('/users/me') be registered before @app.get('/users/{name}')?", ["It does not matter", "Otherwise 'me' is captured as the {name} path parameter", "FastAPI rejects duplicate prefixes", "The second route is never compiled"], 1, "Routes are matched in registration order, so the literal path must be declared before the parameterised one."),
        ("How does FastAPI run a plain def endpoint compared with async def?", ["Both run on the event loop", "Plain def runs in a threadpool, async def on the event loop", "Plain def is refused", "async def runs in a threadpool"], 1, "def endpoints execute in a threadpool so blocking work does not stall the loop, while async def is awaited directly."),
        ("What does raising HTTPException(status_code=404, detail='Missing') produce?", ["A plain-text 404 page", "A JSON 404 response with {'detail': 'Missing'}", "A 422 response", "An unhandled traceback"], 1, "FastAPI converts HTTPException into a JSON response whose detail field carries the message."),
        ("What is the effect of declaring response_model=PublicUser on a route?", ["Documentation only, no filtering", "Extra fields not in PublicUser are stripped from the response", "It disables validation", "It forces a 200 status"], 1, "FastAPI serialises the return value through the model, so undeclared fields never reach the client."),
        ("In def read(q: str = 'all'), where q does not appear in the path template, what kind of parameter is q?", ["Path", "Query", "Body", "Header"], 1, "Any simple parameter that is not part of the path template is read from the query string by FastAPI."),
        ("Given class Item(BaseModel): name: str; price: float = 0.0, what happens if the JSON body omits price?", ["422 validation error", "price is None", "price defaults to 0.0", "TypeError"], 2, "A Pydantic field with a default is optional, so Pydantic fills in 0.0 when the key is absent from the body."),
        ("What does model.model_dump_json() return on a Pydantic v2 model instance?", ["A Python dict", "None", "bytes", "A JSON-encoded string"], 3, "model_dump_json serialises the model straight to a JSON str, while model_dump() is the method that returns a dict."),
        ("What does app.dependency_overrides[get_db] = fake_get_db do?", ["Replaces the dependency, typically for tests", "Deletes the route from the app", "Overrides the OpenAPI document title", "Disables response validation"], 0, "dependency_overrides swaps the implementation behind a Depends dependency at runtime, the standard way to inject fakes in tests."),
    ],
}

IT_LESSONS: dict[str, dict] = {
    "python-basics": {
        "title": "Python Basics",
        "notes": "Python is an interpreted, dynamically typed language: you run source files directly, and names are bound to objects at runtime instead of being locked to a fixed type. Mastering a handful of rules prevents most beginner output-prediction mistakes.\n- Values and types: int, float, str and bool are the everyday building blocks. The / operator always returns a float, // performs floor division that rounds toward negative infinity (so -7 // 2 is -4), and % yields a remainder carrying the sign of the divisor (so -7 % 2 is 1).\n- Operator precedence: ** binds tighter than * and /, and ** is right-associative, so 2 ** 3 ** 2 means 2 ** (3 ** 2) = 512, not 64. Parentheses make intent explicit.\n- Truthiness: 0, 0.0, '', [], {}, () and None are falsy; everything else is truthy. bool('False') is True because a non-empty string is truthy, while bool(0.0) is False.\n- Strings: immutable sequences that support indexing, slicing, concatenation and repetition, and adjacent literals such as 'py' 'thon' concatenate at parse time.\n- Floating point: 0.1 + 0.2 equals 0.30000000000000004 because binary floats cannot represent every decimal fraction, so compare with math.isclose or a tolerance instead of ==.\n- bool subclasses int, so True + True is 2 and type(True + True) is int.\nPredict each line of output before running the code; that habit surfaces precedence and type errors early.",
        "examples": [
            "Predict print(10 // 3, 10 % 3) - it prints 3 1 because 10 divided by 3 leaves remainder 1.",
            "Evaluate 2 ** 3 ** 2 - right-associativity gives 2 ** 9 = 512, not 64.",
            "Test 0.1 + 0.2 == 0.3 - it is False; compare with abs(a - b) < 1e-9 instead.",
        ],
        "practice": [
            "State the type and value of type(5 / 2) and type(5 // 2), and explain why they differ.",
            "Explain why bool('False') is True while bool(0.0) is False.",
            "Compute -7 // 2 and -7 % 2 and justify both results from the definitions of floor division and modulus.",
        ],
        "code": "total = 3 * 2 + 1\nprint(total)\nprint(type(5 / 2))\nprint(2 ** 3 ** 2)\nprint(-7 // 2, -7 % 2)\nprint(bool('False'), bool(0.0))\nprint(0.1 + 0.2 == 0.3)",
    },
    "python-variables": {
        "title": "Variables and Data Types",
        "notes": "In Python a variable is a name bound to an object, not a box that holds a value. Understanding that distinction explains aliasing, mutability and rebinding in one stroke.\n- Assignment binds a name: x = [1, 2] makes x reference a list object. A second name y = x references the same object, so y.append(3) is visible through x as well. To isolate, copy with list(x) or x.copy().\n- Rebinding is not mutation: after a = b = [0], executing a = [1] simply points a at a new list, and b still refers to the original [0].\n- Mutability: lists and dicts are mutable, while tuples, strings and numbers are immutable. a = (1, 2); a[0] = 9 raises TypeError.\n- Dynamic typing: x = 5 followed by x = 'text' is legal, so type hints are documentation rather than enforcement at runtime.\n- is versus ==: == compares value, is compares object identity. For a = 256 and b = 256.0, a == b is True but a is b is False because an int and a float are different objects.\n- Unpacking: x, y = 1, 2 packs a tuple and unpacks it, so x, y = y, x swaps values with no temporary variable.\n- Identifiers: letters, digits and underscores are allowed, but a name cannot start with a digit and cannot be a keyword.\nUse diagrams with arrows from names to objects whenever aliasing questions appear.",
        "examples": [
            "Two names, one list - y = x then y.append(3) changes both; slice or .copy() to separate them.",
            "Rebinding is harmless - a = [1]; b = a; a = [2] leaves b as [1].",
            "Swap in one line - x, y = y, x exchanges the values without a temporary variable.",
        ],
        "practice": [
            "Given a = [1, 2] and b = a[:], what does print(a, b) show after a.append(3)?",
            "For two lists holding the same values, when does `is` return False while `==` returns True?",
            "Classify these as valid or invalid identifiers: 2nd_place, _internal, class, my-var.",
        ],
        "code": "x = [1, 2]\ny = x\ny.append(3)\nprint(x, y)\na = b = [0]\na = [1]\nprint(b)\nx, y = 1, 2\nx, y = y, x\nprint(x, y)\nval = 5\nval = 'text'\nprint(type(val))",
    },
    "python-loops": {
        "title": "Loops and Iteration",
        "notes": "Python has two loop forms, and both iterate over iterators rather than over integer indices.\n- for loops: `for item in iterable:` pulls items one at a time. Works with lists, strings, dicts, tuples, sets and range objects. Iterating a dict yields its keys, so list({'a': 1}) gives ['a'].\n- range: range(start, stop, step) is lazy and memory friendly. range(1, 10, 3) yields 1, 4, 7; len(range(2, 10, 3)) is 3 because the values are 2, 5 and 8. The stop value is never included.\n- while loops: repeat while a condition stays true. Always ensure the condition changes, or the loop runs forever.\n- break and continue: break leaves the nearest enclosing loop immediately; continue skips to the next iteration of that same loop only, which is why continue inside an inner loop never affects the outer loop.\n- Loop else: the else block runs only when the loop completes without break - a clean idiom for search loops.\n- enumerate and zip: enumerate(seq, start=1) yields (index, value) pairs; zip pairs two sequences element-wise and stops at the shorter one.\n- Beware mutating a list while iterating it: appending extends the iteration and removing shifts elements so some are skipped. Iterate over a copy or build a new list with a comprehension.",
        "examples": [
            "Collect evens - evens = [n for n in range(10) if n % 2 == 0].",
            "Search with else - a for/else prints 'not found' only if the loop never executed break.",
            "Indexed iteration - for i, ch in enumerate('abc', start=1) gives (1, 'a'), (2, 'b'), (3, 'c').",
        ],
        "practice": [
            "Write a loop that prints numbers 1 to 20 but 'fizz' for every multiple of 3.",
            "What is len(range(2, 10, 3)) and which values does the range contain?",
            "Explain why removing items from a list while iterating over it can skip elements.",
        ],
        "code": "for i in range(1, 10, 3):\n    print(i)\ntotal = 0\nfor i in range(5):\n    if i == 3:\n        break\n    total += i\nprint(total)\nn = 0\nfor i in range(3):\n    for j in range(3):\n        if j == 1:\n            continue\n        n += 1\nprint(n)",
    },
    "python-functions": {
        "title": "Functions",
        "notes": "Functions are first-class objects in Python: they can be passed as arguments, returned from other functions and stored in data structures.\n- Defining: `def name(args):` runs on call and returns None unless an explicit return is present. A function that only prints therefore returns None.\n- Parameters: positional arguments fill parameters in order, keyword arguments name them. *args collects extra positionals into a tuple and **kwargs collects extra keywords into a dict.\n- Default arguments: evaluated once at definition time, not per call. A mutable default like def f(lst=[]) is shared across every call and grows - a classic bug. Use def f(lst=None) and assign lst = [] inside.\n- Scope: reading a global inside a function works, but assigning to that name makes it local and raises UnboundLocalError. Declare `global count` (or `nonlocal` for an enclosing function) to modify the outer binding.\n- Lambdas: small anonymous functions limited to a single expression, most often used as a key= or filter callback, for example sorted(items, key=lambda x: -x).\n- Decorators: a decorator takes a function and returns a replacement, so @deco above def add wraps add and its extra behaviour applies to every call.\n- Recursion: base case plus smaller subproblem, but Python's default recursion limit is about 1000 frames.\nTest functions with varied inputs, especially empty and default-argument cases.",
        "examples": [
            "Avoid the shared default - rewrite def f(lst=[]) using lst=None so each call gets a fresh list.",
            "Count calls - a decorator with a closure variable records how many times the wrapped function ran.",
            "Argument packing - f(1, 2, a=3) with def f(*args, **kwargs) yields args = (1, 2) and kwargs = {'a': 3}.",
        ],
        "practice": [
            "Repair this so repeated calls are independent: def add_item(item, bucket=[]): bucket.append(item); return bucket.",
            "Given def f(*args, **kwargs), what does f(1, 2, a=3, b=4) return and why?",
            "Explain the UnboundLocalError raised by a function that assigns to a name it also reads.",
        ],
        "code": "def f(lst=None):\n    if lst is None:\n        lst = []\n    lst.append(1)\n    return lst\n\nprint(f(), f())\n\ndef deco(fn):\n    def wrapper(*a, **k):\n        return fn(*a, **k) + 1\n    return wrapper\n\n@deco\ndef add(a, b):\n    return a + b\n\nprint(add(2, 3))",
    },
    "python-oop": {
        "title": "Object-Oriented Programming",
        "notes": "Classes bundle state and behaviour. A class is a blueprint; each instance gets its own attributes while shared state lives on the class.\n- Construction: __init__ initialises a freshly created object, and self is the instance passed implicitly when a method is called as obj.method().\n- Class versus instance attributes: class attributes are shared by all instances, so a counter declared on the class and incremented in __init__ tracks how many objects exist. Assigning c1.x = 5 creates an instance attribute that shadows the class attribute for c1 only, leaving c2.x unchanged.\n- Inheritance: class B(A) reuses A's methods. If B defines __init__ without calling super().__init__(), the parent's initialisation never runs and its attributes are missing, raising AttributeError.\n- MRO: Python resolves methods with C3 linearisation. For D(B, C) where B and C both extend A, the MRO is D, B, C, A, object, so B wins over C.\n- Encapsulation: there is no true private; a name like __x is mangled to _ClassName__x to avoid clashes in subclasses.\n- Properties: @property turns a getter into attribute-style access and lets you validate before setting.\n- Dunders: __str__ is used by print and str, while __repr__ is used in the interpreter and for debugging.\n- Checks: isinstance(obj, cls) respects inheritance, whereas type(obj) is cls demands an exact match.",
        "examples": [
            "Track instances - a class attribute count incremented in __init__ reports how many objects were built.",
            "Diamond inheritance - D(B, C) linearises to [D, B, C, A, object], so B's method is found first.",
            "Guard a value - expose balance through @property and raise in the setter when a negative amount is supplied.",
        ],
        "practice": [
            "Explain the difference between a class attribute and an instance attribute, with a short example.",
            "Write the MRO for class D(B, C) where B(A) and C(A), and say which method wins on a conflict.",
            "Why does print(obj) show __str__ output while the bare name obj in a REPL uses __repr__?",
        ],
        "code": "class Dog:\n    species = 'Canis familiaris'\n    count = 0\n\n    def __init__(self, name):\n        self.name = name\n        Dog.count += 1\n\n    def speak(self):\n        return f'{self.name} says woof'\n\nrex = Dog('Rex')\nprint(rex.speak(), Dog.count, rex.species)",
    },
    "python-file-handling": {
        "title": "File Handling",
        "notes": "Files are handled through file objects, and the with statement is the safe default because it closes the file even when an exception occurs.\n- Opening: open(path) defaults to mode 'r' for reading text and raises FileNotFoundError if the file is missing. 'w' truncates existing content before writing, 'a' appends at the end, 'x' creates exclusively and fails if the file exists, and 'b' switches to binary mode.\n- Writing: fh.write(text) returns the number of characters written, not None. Binary mode requires bytes, so fh.write('abc') on an 'ab' handle raises TypeError.\n- Reading: fh.read() returns the whole file as one string, fh.readline() returns one line, and fh.readlines() returns a list of lines that still carry their trailing newlines.\n- Context manager: `with open(path) as fh:` calls __exit__ and guarantees the handle is released; flush and seek do not close the file.\n- Encoding: specify encoding='utf-8' explicitly so behaviour does not depend on the machine's locale.\n- JSON: json.load(fh) parses from a file object, json.loads(s) parses from a string, json.dump(obj, fh) writes, and json.dumps(obj) returns a string.\n- pathlib: Path(p).read_text(encoding='utf-8') and Path(p).write_text(...) are compact modern equivalents.\nAlways open inside a with block and keep the file mode matched to the operation.",
        "examples": [
            "Safe read - with open(path, encoding='utf-8') as fh: text = fh.read() guarantees closure.",
            "Append a record - open(path, 'a') adds a line without destroying the existing contents.",
            "JSON round-trip - json.dump(obj, fh) to write, then json.load(fh) to read the structure back.",
        ],
        "practice": [
            "What does open('f.txt', 'w') do to content that already exists in f.txt?",
            "Under which condition does fh.write('abc') raise TypeError, and why?",
            "Write code that saves a dict to data.json and reads it back as a dict.",
        ],
        "code": "import json\nfrom pathlib import Path\n\npath = Path('data.json')\nwith path.open('w', encoding='utf-8') as fh:\n    json.dump({'name': 'Ada', 'skills': ['python']}, fh, indent=2)\nwith path.open(encoding='utf-8') as fh:\n    data = json.load(fh)\nprint(data['name'], len(data['skills']))",
    },
    "python-apis": {
        "title": "Working with APIs",
        "notes": "An API exposes resources over HTTP, and a client sends a method plus a URL, optional headers, an optional body, then reads a status code and a response body.\n- Methods: GET reads, POST creates, PUT replaces, PATCH partially updates and DELETE removes. GET requests should have no side effects.\n- Status codes: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 unauthorised, 403 forbidden, 404 Not Found, 422 validation failure, 429 rate limited, 500 server error.\n- requests: requests.get(url, params={'q': 'py'}) builds the query string; requests.post(url, json=payload) sets Content-Type: application/json automatically; custom headers pass through the headers argument.\n- Responses: response.status_code, response.text for the raw body, response.json() for the parsed Python object, and response.raise_for_status() which raises HTTPError on 4xx or 5xx so failures do not pass silently.\n- Credentials: send tokens in an Authorization header such as Bearer <token> rather than in the URL, where they end up in logs and history.\n- httpx: offers the same API and additionally supports timeouts, HTTP/2 and an AsyncClient for concurrent requests with asyncio.gather.\n- Timeouts: always set one, otherwise a stalled connection can block your service indefinitely.\n- Standard library urllib.request is available without installs but is far more verbose than requests or httpx.",
        "examples": [
            "Build a query - requests.get(base, params={'q': 'python', 'page': 2}) produces ?q=python&page=2.",
            "POST JSON - requests.post(url, json={'name': 'Ada'}) sets the JSON content type for you.",
            "Fail loudly - wrap the call in try/except and call response.raise_for_status() before using the body.",
        ],
        "practice": [
            "Which status codes mean created, not found and server error?",
            "Why should an API key be sent in a header instead of a query parameter?",
            "Show how httpx.AsyncClient can fetch two endpoints concurrently with asyncio.gather.",
        ],
        "code": "import httpx\n\nwith httpx.Client(timeout=5.0) as client:\n    r = client.get('https://httpbin.org/get', params={'q': 'python'})\n    print(r.status_code)\n    print(r.json()['args'])",
    },
    "python-fastapi": {
        "title": "FastAPI Fundamentals",
        "notes": "FastAPI builds on Starlette and Pydantic to give you typed routes, automatic documentation and validation straight from the function signature.\n- Path, query and body: a parameter inside the path template like {item_id} is a path parameter; annotating it item_id: int converts '42' to an int and rejects 'abc' with 422. Unannotated simple parameters become query parameters, and a Pydantic BaseModel parameter is parsed from the JSON body.\n- Validation: invalid body fields return 422 Unprocessable Entity with a per-field error list. You can tighten rules with Query(..., min_length=3) or Path(..., ge=1).\n- Status codes: set status_code=201 on a POST route to signal creation; the default success status is otherwise 200.\n- Dependencies: Depends(get_current_user) resolves the function, runs it and injects the result, which is how auth, database sessions and pagination are shared.\n- Errors: raising HTTPException(status_code=404, detail='Missing') becomes a JSON response with a detail key.\n- response_model filters what leaves the server, so internal fields never leak to clients.\n- Route order matters: declare /users/me before /users/{name} or the literal path is swallowed by the parameter.\n- async def versus def: async endpoints run on the event loop and must not block; plain def endpoints run in a threadpool, so blocking libraries are safe there.\n- Explore the generated docs at /docs (Swagger UI) and /redoc during development.",
        "examples": [
            "Typed path parameter - item_id: int converts '42' automatically and returns 422 for 'abc'.",
            "Shared auth - define get_current_user() and accept it via Depends(...) so routes stay small.",
            "Custom success status - @app.post('/items', status_code=201) returns 201 instead of 200.",
        ],
        "practice": [
            "Write a POST route that accepts a Pydantic model, validates it and responds with 201.",
            "Explain why /users/me must be registered before /users/{name}, and what breaks otherwise.",
            "When should a route use async def instead of def, and what goes wrong if you block the loop?",
        ],
        "code": "from fastapi import FastAPI, HTTPException\nfrom pydantic import BaseModel\n\napp = FastAPI()\n\nclass ItemIn(BaseModel):\n    name: str\n    price: float\n\n@app.post('/items', status_code=201)\ndef create_item(item: ItemIn):\n    if item.price < 0:\n        raise HTTPException(status_code=400, detail='Negative price')\n    return {'name': item.name, 'price': item.price}",
    },
}


def get_it(slug: str) -> list[dict]:
    return [
        {"question_text": q, "options": list(opts), "correct_index": idx, "explanation": expl, "difficulty": "beginner"}
        for q, opts, idx, expl in IT_BANKS[slug]
    ]
