"""IT question banks + lessons: SQL and DSA learning paths."""
from __future__ import annotations

IT_BANKS: dict[str, list[tuple]] = {
    "sql-basic-queries": [
        ("Which SQL keyword eliminates duplicate rows from a SELECT result?", ["UNIQUE", "DISTINCT", "DUPLICATE", "DEDUP"], 1, "DISTINCT keeps only unique combinations of the selected columns."),
        ("What does the predicate `WHERE name = NULL` return?", ["All rows of the table", "No rows at all", "Rows where name is an empty string", "A syntax error"], 1, "NULL compares to UNKNOWN, which is never TRUE, so you must use IS NULL instead."),
        ("Table Users has 5 rows and `email` is NULL in 2 of them. What does `SELECT COUNT(*), COUNT(email) FROM Users` return?", ["5, 5", "5, 3", "3, 3", "3, 5"], 1, "COUNT(*) counts rows while COUNT(column) skips NULL values."),
        ("What is the default sort direction of ORDER BY in SQL?", ["Descending", "Ascending", "Random", "It depends on the primary key"], 1, "ORDER BY col is shorthand for ORDER BY col ASC."),
        ("Which value does NOT match the pattern `LIKE 'A_C'`?", ["'ABC'", "'AC'", "'AXC'", "'A1C'"], 1, "Underscore matches exactly one character, so the two-character string 'AC' cannot match."),
        ("Table Orders: (1,'Ann',100), (2,'Bob',200), (3,'Ann',50). What does `SELECT customer FROM Orders ORDER BY amount DESC` produce?", ["Ann, Bob, Ann", "Bob, Ann, Ann", "Bob, Ann", "Ann, Ann, Bob"], 1, "Sorting by amount descending gives Bob(200), Ann(100), Ann(50) and no DISTINCT was applied."),
        ("Which clause may legally reference a column alias defined in the SELECT list?", ["WHERE", "ORDER BY", "FROM", "GROUP BY"], 1, "Aliases are resolved after row filtering, so ORDER BY can use them but WHERE cannot."),
        ("What is the result of the expression `SELECT 10 + NULL`?", ["10", "0", "NULL", "An error"], 2, "Any arithmetic involving NULL yields NULL because NULL means unknown."),
        ("Which value does `TRIM` return for the string '  hi  ' in standard SQL?", ["'hi'", "'  hi'", "'hi  '", "NULL"], 0, "TRIM removes leading and trailing space characters, leaving the inner text unchanged."),
        ("What does `COALESCE(NULL, NULL, 'default')` return?", ["An error", "NULL", "'default'", "0"], 2, "COALESCE returns its first non-NULL argument, so the third value is chosen."),
        ("Table Users ids: 1, 2, 3, 4, 5. What does `SELECT id FROM Users ORDER BY id DESC LIMIT 2` return?", ["1, 2", "4, 5", "3, 4", "5, 4"], 3, "Descending order puts 5 first and 4 second, and LIMIT 2 keeps only those two rows."),
        ("Table T: (1,'a'), (2,'b'), (3,'c'), (NULL,'d'). What does `SELECT * FROM T WHERE id <> 2` return?", ["Rows 1, 2 and 3", "Rows 1 and 3", "Rows 1, 3 and the NULL-id row", "All four rows"], 1, "`<>` excludes id 2, and the NULL row is dropped too because NULL <> 2 is UNKNOWN."),
    ],
    "sql-joins": [
        ("Which JOIN keeps only rows that have a match in both tables?", ["LEFT JOIN", "INNER JOIN", "FULL OUTER JOIN", "CROSS JOIN"], 1, "An INNER JOIN returns the intersection of both tables on the join condition."),
        ("Table A ids: 1, 2, 3. Table B ids: 2, 3, 4. What does `SELECT A.id FROM A LEFT JOIN B ON A.id = B.id` return?", ["1, 2, 3", "2, 3", "1, 2, 3, 4", "2, 3, 4"], 0, "LEFT JOIN keeps every A row; id 1 has no match but is still returned."),
        ("Table A has 3 rows and Table B has 4 rows. How many rows does `SELECT * FROM A CROSS JOIN B` produce?", ["7", "12", "3", "4"], 1, "A cross join is the Cartesian product: 3 * 4 = 12 rows."),
        ("What is a join of a table with itself called?", ["SELF JOIN", "NATURAL JOIN", "EQUI JOIN", "THETA JOIN"], 0, "A SELF JOIN gives the table two different aliases and joins them."),
        ("A has ids 1, 2 and B has ids 2, 3. How many id values does a FULL OUTER JOIN of A and B return?", ["1 row: 2", "2 rows: 2", "3 rows: 1, 2, 3", "4 rows: 1, 2, 2, 3"], 2, "FULL OUTER JOIN unions the matched pair with the unmatched rows from each side: 1, 2, 3."),
        ("Why can `LEFT JOIN B ON ... WHERE B.col = 'x'` behave like an INNER JOIN?", ["Because ON and WHERE are always equivalent", "Because filtering the right table discards the NULL-extended rows", "Because LEFT JOIN is invalid with WHERE", "Because the optimizer rewrites it"], 1, "Unmatched left rows get NULLs for B, and the WHERE predicate rejects them."),
        ("What happens when you join on a column that contains NULLs?", ["NULLs match each other", "NULLs never match anything", "An error is raised", "Only the first NULL matches"], 1, "NULL = NULL evaluates to UNKNOWN, so null keys never join."),
        ("Which join produces every possible combination of rows from two tables?", ["INNER JOIN", "CROSS JOIN", "LEFT JOIN", "SEMI JOIN"], 1, "CROSS JOIN pairs each row with every row of the other table."),
        ("Table A ids: 1, 2. Table B ids: 2, 2, 3. How many rows does `SELECT * FROM A JOIN B ON A.id = B.id` return?", ["6", "4", "3", "2"], 3, "Only id 2 matches, and it pairs with each of B's two id-2 rows, giving 2 rows."),
        ("Table A ids: 1, 2, 3. Table B ids: 2, 3, 4. What does `SELECT B.id FROM A RIGHT JOIN B ON A.id = B.id` return?", ["2, 3, 4", "1, 2, 3", "2, 3", "1, 2, 3, 4"], 0, "RIGHT JOIN keeps every B row; ids 2 and 3 match A while id 4 is kept with NULLs."),
        ("Tables Orders(o_id, cust) and Customers(c_id, name). Which query returns customers who have never placed an order?", ["SELECT c.* FROM Customers c JOIN Orders o ON o.cust = c.c_id", "SELECT c.* FROM Customers c WHERE c.c_id IN (SELECT cust FROM Orders)", "SELECT c.* FROM Customers c LEFT JOIN Orders o ON o.cust = c.c_id WHERE o.o_id IS NULL", "SELECT c.* FROM Customers c, Orders o WHERE o.cust = c.c_id"], 2, "The left anti-join keeps every customer and the IS NULL test keeps only those with no matching order."),
        ("A NATURAL JOIN between two tables does what?", ["Cross joins the two tables", "Joins on every column that has the same name in both tables", "Requires an explicit ON clause", "Only matches primary keys"], 1, "NATURAL JOIN automatically equates all identically named columns, so shared names decide the match."),
    ],
    "sql-group-by": [
        ("Which clause filters rows BEFORE grouping happens?", ["HAVING", "WHERE", "ORDER BY", "LIMIT"], 1, "WHERE filters individual rows; HAVING filters the groups produced by GROUP BY."),
        ("Why can an aggregate function not appear in a WHERE clause?", ["Because aggregates are illegal in SQL", "Because WHERE runs before grouping, when aggregates do not exist yet", "Because of a type mismatch", "Because of index usage"], 1, "Aggregation happens after row filtering, so group filters belong in HAVING."),
        ("What is AVG of the values 10, NULL, 30?", ["20", "13.33", "NULL", "10"], 0, "SQL's AVG ignores NULLs, so it computes (10 + 30) / 2 = 20."),
        ("What does SUM return when every value in the column is NULL?", ["0", "NULL", "An error", "-1"], 1, "Aggregates return NULL over an empty set of non-NULL values; only COUNT returns 0."),
        ("Table Sales: ('East',10), ('East',20), ('West',5). What does `SELECT region, SUM(amount) FROM Sales GROUP BY region` return?", ["East,30 and West,5", "East,20 and West,5", "35", "East,10 and West,5"], 0, "Rows are grouped by region, summing East to 30 and West to 5."),
        ("What does COUNT(DISTINCT customer) compute?", ["The total number of orders", "The number of different customers", "The number of NULL customers", "Customers sorted alphabetically"], 1, "DISTINCT collapses duplicate values before they are counted."),
        ("In standard SQL, what is true of columns in the SELECT list that are not aggregated?", ["They must appear in GROUP BY or be aggregated", "They may be any column at all", "Only primary keys may be selected", "GROUP BY must be paired with HAVING"], 0, "Non-aggregated output columns have to be part of the grouping key."),
        ("In `SELECT dept FROM emp WHERE salary > 5000 GROUP BY dept HAVING COUNT(*) > 2`, what does HAVING do?", ["Filters employees earning over 5000", "Keeps only departments with more than 2 matching employees", "Sorts the departments", "Limits the result to 2 rows"], 1, "WHERE keeps high earners, then HAVING keeps groups whose surviving row count exceeds 2."),
        ("Table Emp: ('Eng','Ann'), ('Eng','Bob'), ('HR','Cy'). What does `SELECT dept FROM Emp GROUP BY dept HAVING COUNT(*) > 1` return?", ["HR", "Eng, HR", "Eng", "Ann, Bob, Cy"], 2, "Only the Eng group has more than one row, so HAVING drops the single-row HR group."),
        ("Which statement about rows removed by WHERE is correct?", ["They are still included in the groups", "They form a group of their own", "They cause HAVING to fail", "They are excluded from every group"], 3, "WHERE runs before GROUP BY, so rejected rows never reach the grouping stage."),
        ("When the grouping column contains NULLs, GROUP BY treats them as:", ["A single group of their own", "Rows to discard", "A syntax error", "Rows merged into the first group"], 0, "NULLs compare equal to each other for grouping, so they collect into one NULL group."),
        ("Table Sales: ('East',10), ('East',20), ('West',5). What does `SELECT region, COUNT(*) FROM Sales GROUP BY region ORDER BY COUNT(*) DESC` return?", ["West,1 then East,2", "East,2 then West,1", "East,30 then West,5", "East,10 then West,5"], 1, "East has two rows and West one, and ORDER BY COUNT(*) DESC places East first."),
    ],
    "sql-subqueries": [
        ("A subquery that is used directly with the `=` operator must return:", ["Exactly one row and one column", "Any number of rows", "At least two columns", "Always zero rows"], 0, "A scalar subquery returns a single value; more than one row raises an error."),
        ("A correlated subquery is one that:", ["Has no FROM clause", "References columns of the outer query and is re-evaluated for each outer row", "Always executes first", "Appears only in the FROM clause"], 1, "Correlation means the inner query depends on the current outer row's values."),
        ("What does `EXISTS (subquery)` evaluate to when the subquery returns at least one row?", ["TRUE", "FALSE", "NULL", "The matched row itself"], 0, "EXISTS only tests whether the result set is non-empty and stops at the first row."),
        ("Why can `WHERE id NOT IN (SELECT id FROM t)` return zero rows even when t is small?", ["Because NOT IN is invalid SQL", "Because a single NULL in the subquery makes the condition UNKNOWN for every row", "Because of index usage", "Because of implicit sorting"], 1, "NULL comparisons yield UNKNOWN, so NOT IN never becomes TRUE."),
        ("Which expression is equivalent to `x = ANY (subquery)`?", ["x IN (subquery)", "x = ALL (subquery)", "x EXISTS (subquery)", "x = SOME-none"], 0, "= ANY is true when x equals at least one subquery value, exactly like IN."),
        ("For a non-correlated subquery, which part is normally executed first?", ["The inner subquery", "The outer query", "Both at the same time", "The ORDER BY clause"], 0, "The independent inner query is resolved first and its result is then used outside."),
        ("A derived table written in the FROM clause must usually have:", ["A column named id", "An alias", "A primary key", "A LIMIT clause"], 1, "Most SQL dialects require an alias for a subquery used as a table."),
        ("Which clause most often contains a subquery to restrict which rows are returned?", ["WHERE", "FROM only", "GROUP BY only", "SET"], 0, "Scalar, IN, EXISTS and correlated subqueries are all commonly placed in WHERE."),
        ("Table emp(name, dept, salary). What does `SELECT name FROM emp e WHERE EXISTS (SELECT 1 FROM emp m WHERE m.dept = e.dept AND m.salary > e.salary)` return?", ["Employees earning the top salary in their department", "Employees who have no higher-paid colleague", "Employees who have a higher-paid colleague in the same department", "Every employee in the table"], 2, "EXISTS is true only when some same-dept row has a greater salary, so top earners are excluded."),
        ("What does `SELECT name FROM emp WHERE salary = (SELECT MAX(salary) FROM emp)` return when two employees tie for the highest salary?", ["Only the first tied employee", "An error is raised", "No rows", "Both tied employees"], 3, "The scalar subquery yields a single maximum value, and every row equal to it satisfies the predicate."),
        ("Which rewrite is safe when the subquery of `id NOT IN (...)` may contain NULLs?", ["id IN (SELECT id FROM t)", "NOT EXISTS (SELECT 1 FROM t WHERE t.id = e.id)", "id = ANY (SELECT id FROM t)", "id > ALL (SELECT id FROM t)"], 1, "NOT EXISTS never becomes UNKNOWN because of a NULL, whereas IN, = ANY and > ALL all trap on NULL."),
        ("The subquery in `WHERE salary > ANY (SELECT salary FROM team WHERE role = 'lead')` returns 5, 10 and 20. Which salaries satisfy the condition?", ["Any salary greater than 5", "Only salaries greater than 20", "Only salaries equal to 5, 10 or 20", "No salary can satisfy it"], 0, "ANY means greater than at least one value, so the condition equals salary > MIN(...), which is 5."),
    ],
    "sql-window-functions": [
        ("Which clause splits rows into groups for a window function without collapsing them?", ["PARTITION BY", "GROUP BY", "ORDER BY", "DISTINCT"], 0, "PARTITION BY divides the result set into independent frames while keeping every row."),
        ("With ORDER BY in the OVER clause and no explicit frame, what is the default window frame of a windowed aggregate?", ["Rows between unbounded preceding and current row", "The whole partition", "Only the current row", "Unbounded following up to the current row"], 0, "The default becomes a running total from the start of the partition through the current row."),
        ("With no ORDER BY inside OVER, what does a window aggregate consider?", ["Only the current row", "The entire partition", "Nothing", "Rows in insertion order only"], 1, "Without ORDER BY the frame is the whole partition, which mirrors the GROUP BY result."),
        ("How do RANK() and DENSE_RANK() rank the ordered scores 90, 80, 80, 70?", ["Both give 1,2,2,3", "RANK gives 1,2,2,4 and DENSE_RANK gives 1,2,2,3", "Both give 1,2,2,4", "RANK gives 1,2,3,4 and DENSE_RANK gives 1,2,2,3"], 1, "Both keep ties equal; RANK then skips to 4 while DENSE_RANK continues at 3."),
        ("Which function reads a value from an earlier row of the same partition?", ["LAG", "LEAD", "NTILE", "FIRST_VALUE"], 0, "LAG looks backwards by an offset while LEAD looks forwards."),
        ("What does NTILE(4) OVER (ORDER BY score) do?", ["Ranks the scores", "Splits the rows into 4 roughly equal buckets", "Groups by 4 columns", "Returns only the top 4 rows"], 1, "NTILE divides the ordered rows into n buckets of as-equal size as possible."),
        ("Why is `WHERE ROW_NUMBER() OVER (...) = 1` invalid?", ["Because row numbers are strings", "Because window functions are evaluated after WHERE", "Because WHERE only accepts indexes", "Because it is always a syntax error"], 1, "Filter window results in an outer query, a CTE or QUALIFY instead."),
        ("ROW_NUMBER() OVER (ORDER BY score DESC) over scores 90, 80, 80 yields:", ["1, 2, 2", "1, 2, 3", "1, 1, 2", "2, 3, 4"], 1, "ROW_NUMBER always produces unique consecutive numbers even when values tie."),
        ("Table Emp: (Ada,Sales,100), (Bob,Sales,200), (Cy,Eng,150). What does `SELECT name, SUM(sal) OVER (PARTITION BY dept)` output for Ada?", ["100", "A running total", "300", "450"], 2, "With no ORDER BY the frame is the whole partition, so every Sales row shows the Sales total of 300."),
        ("What does `LEAD(sal, 1) OVER (ORDER BY id)` produce for the last row of a partition?", ["The first row's salary", "The previous row's salary", "The current row's salary", "NULL"], 3, "LEAD looks one row forward, and no row exists past the partition's end, so it yields NULL."),
        ("Which frame clause computes a three-row moving average that includes the current row?", ["ROWS BETWEEN 3 PRECEDING AND CURRENT ROW", "ROWS BETWEEN 2 PRECEDING AND CURRENT ROW", "ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW", "ROWS BETWEEN CURRENT ROW AND 2 FOLLOWING"], 1, "Two preceding rows plus the current row make exactly three rows in the frame."),
        ("How do you compute each row's share of its partition total with a window function?", ["x / SUM(x) OVER (PARTITION BY g)", "x / COUNT(*) OVER ()", "x - AVG(x) OVER (PARTITION BY g)", "NTILE(100) OVER (PARTITION BY g)"], 0, "Dividing the row value by the partition sum yields a per-row fraction of the group total."),
    ],
    "dsa-arrays": [
        ("Average time to access element i of an array by index is:", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 0, "Elements sit at contiguous addresses computed as base + i * element_size."),
        ("Worst-case time to insert an element at the front of a dynamic array is:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "Every existing element must shift one position to the right."),
        ("Amortized time to append an item to a resizable array such as a Python list is:", ["O(n)", "O(log n)", "O(1)", "O(n log n)"], 2, "Occasional resizing spreads the copy cost, so appending is O(1) amortized."),
        ("Time complexity of the two-sum approach that uses a hash set is:", ["O(n)", "O(n^2)", "O(log n)", "O(n^3)"], 0, "Each element is looked up and inserted into the set exactly once."),
        ("Best-case time to search for a value in an unsorted array is:", ["O(1)", "O(n)", "O(log n)", "O(n log n)"], 0, "The target may be the very first element that is inspected."),
        ("Kadane's algorithm for maximum subarray sum runs in:", ["O(n^2) time and O(1) space", "O(n) time and O(1) space", "O(n) time and O(n) space", "O(log n) time"], 1, "A single pass keeps a running current sum using constant extra memory."),
        ("Deleting the middle element of an array takes:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "All elements after the hole must be shifted left to keep the array dense."),
        ("Storing n integers in an array uses how much space?", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "There is one slot per element, giving linear space usage."),
        ("Time complexity of finding the minimum value in an unsorted array of n elements:", ["O(1)", "O(n)", "O(log n)", "O(n log n)"], 1, "Every element may be the minimum, so all n entries must be examined in the worst case."),
        ("lst = [0, 1, 2, 3, 4]. What does `lst[1:4]` evaluate to?", ["[1, 2, 3, 4]", "[0, 1, 2, 3]", "[2, 3, 4]", "[1, 2, 3]"], 3, "Slicing includes index 1 and stops just before index 4, so indices 1, 2 and 3 are copied."),
        ("Time complexity of binary search on a sorted array of n elements:", ["O(log n)", "O(n)", "O(1)", "O(n log n)"], 0, "Each comparison discards half of the remaining search space, halving the range each step."),
        ("Removing duplicates from a sorted array with a slow pointer and a fast pointer takes:", ["O(n) time and O(n) space", "O(n log n) time and O(1) space", "O(n) time and O(1) space", "O(n^2) time and O(1) space"], 2, "Both pointers make a single pass over the array and only a couple of indices are stored."),
    ],
    "dsa-strings": [
        ("Checking whether a string is a palindrome takes:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "Every character has to be inspected at least once, so the lower bound is linear."),
        ("Best time to test whether two strings are anagrams using character counts is:", ["O(n)", "O(n^2)", "O(log n)", "O(n log n)"], 0, "One pass builds the frequency maps and a second pass compares them."),
        ("Why is repeatedly doing `s += word` inside a loop inefficient in Python?", ["Strings are mutable but slow", "Each concatenation copies the whole string, making the loop O(n^2)", "It raises an error", "It uses O(1) space"], 1, "Strings are immutable, so collect parts in a list and call join once."),
        ("The KMP pattern matching algorithm runs in:", ["O(n*m)", "O(n+m)", "O(m log n)", "O(n)"], 1, "Its failure function prevents re-comparing characters, giving linear overall time."),
        ("Reversing a string in place in Python is impossible because:", ["Strings are immutable", "Strings are always too large", "There is no reverse function", "Strings live on the stack"], 0, "Any seeming modification builds a brand new string object."),
        ("The longest substring without repeating characters can be found in O(n) using:", ["A sliding window with a set or map", "Divide and conquer only", "A stack only", "Brute force only"], 0, "Two pointers expand and shrink the window while all characters stay unique."),
        ("A subsequence differs from a substring in that its characters:", ["Must be adjacent", "Need not be adjacent but must keep their order", "May appear in any order", "Must all be unique"], 1, "Subsequences preserve relative order but are allowed to skip characters."),
        ("Counting the vowels in a string of length n takes:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "Each character is examined exactly once."),
        ("s = 'hello'. What does `s[1:4]` return?", ["'hel'", "'hello'", "'ello'", "'ell'"], 3, "The slice starts at index 1 ('e') and stops before index 4, giving characters 1 through 3."),
        ("The naive substring search that tries the pattern at every position of an n-character text with an m-character pattern runs in:", ["O(n)", "O(n + m)", "O(n*m)", "O(m log n)"], 2, "In the worst case every position triggers a full m-character comparison, giving n times m work."),
        ("Counting the distinct characters in a string of length n takes:", ["O(n log n) time and O(k) space", "O(n) time and O(k) space, where k is the number of distinct characters kept", "O(n^2) time and O(1) space", "O(log n) time"], 1, "One pass inserts each character into a set, costing O(n) time and space proportional to the distinct characters."),
        ("Sorting the characters of a string of length n takes:", ["O(n log n)", "O(n)", "O(n^2)", "O(log n)"], 0, "Converting to a list of characters and applying a comparison sort gives the usual n log n bound."),
    ],
    "dsa-linked-lists": [
        ("Inserting a node at the head of a singly linked list takes:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 0, "Only the head pointer and the new node's next pointer need to change."),
        ("Inserting at the tail of a singly linked list without a tail pointer is:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 2, "You must walk the entire list to locate the last node."),
        ("Deleting a known node in a doubly linked list takes:", ["O(1)", "O(log n)", "O(n)", "O(n^2)"], 0, "The neighbours are re-linked directly through the node's own prev and next pointers."),
        ("Floyd's cycle detection algorithm uses:", ["Two pointers moving at different speeds", "A hash set of every node", "A stack", "Recursion only"], 0, "Tortoise and hare meet when a cycle exists, in O(n) time and O(1) space."),
        ("Finding the middle of a linked list with slow and fast pointers costs:", ["O(n) time and O(1) space", "O(n) time and O(n) space", "O(n^2) time", "O(log n) time"], 0, "The fast pointer advances twice as fast, so the slow pointer lands in the middle."),
        ("Searching for a value in an unsorted linked list is:", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 2, "Without random access, nodes must be visited one after another."),
        ("Reversing a linked list iteratively uses:", ["O(n) time and O(1) extra space", "O(n) time and O(n) space", "O(n^2) time", "O(1) time"], 0, "Three pointers (prev, curr, next) are enough to flip every link."),
        ("Compared with an array, a linked list's main advantage is:", ["Random access in O(1)", "No element shifting when inserting at a known node", "Better cache locality", "Lower total memory"], 1, "Insertion only relinks pointers, whereas arrays must shift elements."),
        ("Inserting a node immediately BEFORE a given node in a singly linked list, given only a reference to that node, takes:", ["O(1)", "O(log n)", "O(n^2)", "O(n)"], 3, "Without a prev pointer the predecessor must be found by walking from the head."),
        ("Reversing the list 1 -> 2 -> 3 iteratively produces:", ["1 -> 2 -> 3", "3 -> 2 -> 1", "3 -> 1 -> 2", "2 -> 3 -> 1"], 1, "Each node's next pointer is flipped to the previous node, so the head becomes the former tail."),
        ("Compared with a singly linked list, a doubly linked list stores per node:", ["Two extra pointers", "No extra pointers", "One extra prev pointer", "A second copy of the data"], 2, "The node gains a prev reference in addition to next, doubling the pointer count."),
        ("The call-stack space used by a recursive traversal of an n-node linked list in the worst case is:", ["O(n)", "O(1)", "O(log n)", "O(n^2)"], 0, "Each node adds one frame before the base case is reached, so the stack grows linearly with n."),
    ],
    "dsa-stacks": [
        ("A stack follows which ordering discipline?", ["FIFO", "LIFO", "Priority order", "Random order"], 1, "The last element pushed is the first element popped."),
        ("Time complexity of push and pop on a stack implemented with an array or linked list is:", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 0, "Both operations touch only the top element."),
        ("Matching parentheses is solved with a stack because:", ["Stacks sort data", "An opening bracket must be closed in reverse order, which is LIFO", "Stacks are always faster than arrays", "It requires recursion"], 1, "Nesting order is exactly the last-in-first-out behaviour of a stack."),
        ("Evaluating a postfix expression uses a:", ["Queue", "Stack", "Heap", "Graph"], 1, "Operands are pushed and each operator pops its operands then pushes the result."),
        ("Which traversal of a binary tree is naturally implemented with a stack?", ["Level order", "Depth first order (pre, in or post)", "Breadth first order", "Only zigzag order"], 1, "DFS keeps an explicit stack, or relies on the call stack through recursion."),
        ("Breadth-first search of a graph is implemented with a:", ["Stack", "Queue", "Heap", "Set"], 1, "BFS explores vertices in first-come-first-served order, which requires FIFO."),
        ("Deep or infinite recursion exhausting the call stack causes:", ["A compile error", "A stack overflow", "A heap error", "A logic error only"], 1, "Each recursive call consumes a frame until the fixed stack size is exceeded."),
        ("Finding the minimum element of a stack in O(1) time usually requires:", ["A second auxiliary stack", "Sorting the stack first", "A separate linked list", "Nothing extra at all"], 0, "A parallel stack (or an embedded min value) records the minimum up to each level."),
        ("In the monotonic-stack approach to the next-greater-element problem, which elements are popped when processing the current value?", ["Elements greater than the current value", "Elements waiting to become the answer", "Elements smaller than the current value", "Every element in the stack"], 2, "The current value is the next greater for any smaller element below it, so those elements are resolved and removed."),
        ("The extra space used by evaluating a postfix expression with n tokens is:", ["O(1) always", "O(log n)", "O(n^2)", "O(n), because the operand stack may hold every operand"], 3, "All n tokens could be operands, filling the stack before any operator pops from it."),
        ("Converting an infix expression to postfix notation requires a:", ["Operator stack", "Queue", "Binary tree", "Heap"], 0, "Operators are held on a stack so they can be emitted in precedence and associativity order."),
        ("After push(1), push(2), pop(), push(3), what does top() return?", ["1", "3", "2", "The stack is empty"], 1, "The pop removes 2, leaving 1, and the subsequent push of 3 puts 3 on top."),
    ],
    "dsa-queues": [
        ("A queue follows which ordering discipline?", ["LIFO", "FIFO", "Priority order", "Random order"], 1, "The first element enqueued is the first element dequeued."),
        ("Enqueue and dequeue on a properly implemented queue take:", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 0, "The front and rear pointers are updated directly without scanning."),
        ("Which data structure does breadth-first search use?", ["Stack", "Queue", "Heap", "Hash set"], 1, "BFS explores neighbours level by level, which needs FIFO ordering."),
        ("Round-robin CPU scheduling, where each job gets a fixed time slice, uses a:", ["Stack", "Queue", "Binary tree", "Hash map"], 1, "A job that runs out of its slice is re-enqueued at the back."),
        ("The sliding window maximum problem can be solved in O(n) with:", ["A stack", "A monotonic deque", "A full sort", "A binary search tree only"], 1, "The deque keeps candidates in decreasing order and drops indices that left the window."),
        ("Implementing a queue with two stacks gives an amortized cost of:", ["O(1) per operation", "O(n) per operation", "O(log n) per operation", "O(n^2) per operation"], 0, "Each element moves between the two stacks at most once in its lifetime."),
        ("An array-based queue whose head and tail indices wrap around is called a:", ["Priority queue", "Circular queue", "Deque", "Stack"], 1, "Wrapping reuses emptied slots instead of permanently wasting array space."),
        ("Removing an element from an empty queue is a queue:", ["Underflow", "Overflow", "Deadlock", "Dead path"], 0, "Reading from an empty queue is defined as queue underflow."),
        ("Enqueue 1, 2, 3; dequeue twice; enqueue 4. What value is at the front of the queue?", ["1", "4", "3", "2"], 2, "Two dequeues remove 1 and 2, leaving 3 at the front; 4 is enqueued behind it."),
        ("A queue whose linked list keeps only a rear pointer (no head pointer) makes dequeue:", ["O(1)", "O(log n)", "O(n log n)", "O(n)"], 3, "Without a head reference the front must be located by traversing from the rear, which is linear."),
        ("Accessing both ends of a deque takes:", ["O(1) per operation", "O(log n)", "O(n)", "O(n log n)"], 0, "A deque maintains head and tail links, so insertion and removal at either end are constant time."),
        ("During breadth-first search, the queue holds:", ["Only the vertices already visited", "Vertices that have been discovered but not yet explored", "The current depth-first path", "Every edge of the graph"], 1, "A vertex is enqueued when discovered and dequeued when its neighbours are examined."),
    ],
    "dsa-trees": [
        ("Inorder traversal of a binary search tree visits nodes in:", ["Reverse sorted order", "Ascending sorted order", "Level order", "Random order"], 1, "Left subtree, root, right subtree yields the keys in ascending order."),
        ("Preorder traversal visits nodes in which order?", ["Left, root, right", "Root, left, right", "Left, right, root", "Level by level"], 1, "Preorder emits the root before recursing into each subtree."),
        ("Postorder traversal visits nodes in which order?", ["Root first, then children", "Left, right, root", "Level order", "Right only"], 1, "Both children are processed before the parent, which suits deletion and cleanup."),
        ("A tree with n nodes has exactly how many edges?", ["n", "n-1", "n+1", "2n"], 1, "A tree is connected and acyclic, so edges always equal nodes minus one."),
        ("Level-order traversal of a tree uses a:", ["Stack", "Queue", "Heap", "Hash set"], 1, "A queue processes nodes in the exact order they are discovered."),
        ("In a zero-based array representation of a complete binary tree, the left child of index i is at:", ["2i", "2i+1", "2i+2", "i+1"], 1, "Children of index i live at 2i+1 and 2i+2 under zero-based indexing."),
        ("Searching a height-balanced BST of n nodes takes:", ["O(1)", "O(log n)", "O(n)", "O(n log n)"], 1, "Balancing keeps the tree height logarithmic in the number of nodes."),
        ("The maximum number of nodes at depth d of a binary tree is:", ["d", "2^d", "2^d - 1", "n"], 1, "Depth 0 holds 1 node, depth 1 up to 2, depth 2 up to 4, doubling each level."),
        ("When deleting a BST node that has two children, which node is normally moved into its place?", ["Its in-order predecessor or successor", "The leftmost node of the whole tree", "Any leaf node", "A newly allocated node with the same key"], 0, "The predecessor (max of the left subtree) or successor (min of the right subtree) replaces the key without breaking BST order."),
        ("A binary tree has root A with left child B and right child C, both leaves. What is its preorder traversal?", ["B, A, C", "B, C, A", "A, B, C", "A, C, B"], 2, "Preorder visits the root first, then the left subtree, then the right subtree."),
        ("The height of a degenerate (skewed) binary tree with n nodes, counting the root as height 0, is:", ["log2(n)", "n / 2", "1", "n - 1"], 3, "Each level holds a single node, so n nodes form a chain of n-1 edges below the root."),
        ("A full binary tree, where every node has 0 or 2 children, with i internal nodes has how many leaves?", ["i - 1", "i + 1", "2i", "2^i"], 1, "The two children per internal node plus the root's single slot give leaves = internal + 1."),
    ],
    "dsa-graphs": [
        ("Time complexity of DFS on an adjacency list with V vertices and E edges is:", ["O(V)", "O(V+E)", "O(V^2)", "O(E log E)"], 1, "Each vertex and each edge is processed a constant number of times."),
        ("Space complexity of an adjacency matrix representation is:", ["O(V+E)", "O(V^2)", "O(E)", "O(V log V)"], 1, "The matrix holds one cell for every possible pair of vertices."),
        ("Topological sorting is defined only for:", ["Any graph", "Directed acyclic graphs", "Undirected graphs", "Weighted graphs"], 1, "A cycle makes a valid linear ordering of the vertices impossible."),
        ("Which algorithm finds single-source shortest paths when all edge weights are non-negative?", ["Bellman-Ford", "Dijkstra", "Floyd-Warshall", "Prim"], 1, "Dijkstra greedily finalises the closest unsettled vertex using a priority queue."),
        ("Which shortest-path algorithm tolerates negative edge weights?", ["Dijkstra", "Prim", "Bellman-Ford", "Kruskal"], 2, "Bellman-Ford relaxes all edges V-1 times and can also detect negative cycles."),
        ("Detecting a cycle in an undirected graph with DFS must track:", ["Edge weights", "The parent vertex", "Nothing at all", "Only vertex degrees"], 1, "Reaching an already visited vertex that is not the parent proves a cycle exists."),
        ("A minimum spanning tree of a graph with V vertices contains how many edges?", ["V", "V-1", "V+1", "2V"], 1, "An MST is a tree that spans all V vertices, so it has V-1 edges."),
        ("Checking whether a graph is bipartite is done by:", ["Two-colouring with BFS or DFS", "Running Dijkstra", "Sorting the vertices", "Counting degrees only"], 0, "If no edge joins two vertices of the same colour, the graph is bipartite."),
        ("Using Kahn's algorithm for topological sort, a cycle is detected when:", ["An edge points backward in the produced order", "A vertex has in-degree greater than one", "The graph contains more than one source", "Vertices remain unprocessed after the queue empties"], 3, "A cycle keeps its vertices at non-zero in-degree forever, so they are never enqueued and the output is short."),
        ("Dijkstra's algorithm with a binary heap, an adjacency list, V vertices and E edges runs in:", ["O((V + E) log V)", "O(V^2)", "O(V*E)", "O(E)"], 0, "Each vertex and edge triggers at most one heap operation costing O(log V)."),
        ("The Floyd-Warshall algorithm computes:", ["Single-source shortest paths", "A minimum spanning tree", "All-pairs shortest paths", "A maximum flow"], 2, "It relaxes paths through every intermediate vertex, producing distances between all pairs of vertices."),
        ("An adjacency list for an undirected graph with V vertices and E edges stores how many neighbour entries?", ["V * V", "2E", "E", "V + E"], 1, "Each undirected edge appears once in each endpoint's list, doubling the entry count."),
    ],
    "dsa-dp": [
        ("Which property means an optimal solution is built from optimal solutions of smaller subproblems?", ["Optimal substructure", "Overlapping subproblems", "Greedy choice property", "Divide and conquer"], 0, "Optimal substructure is what allows recursion on smaller instances."),
        ("Memoization in dynamic programming means:", ["Sorting the input first", "Caching subproblem results so each is computed once", "Using only iterative loops", "Throwing away previous results"], 1, "Storing answers turns exponential recursion into polynomial time."),
        ("Bottom-up dynamic programming builds its solution:", ["From the smallest subproblems upward", "From the final answer downward", "In random order", "Only with recursion"], 0, "Tabulation iterates over base cases and grows toward the target problem."),
        ("0/1 knapsack solved with DP runs in:", ["O(2^n)", "O(nW) where W is the capacity", "O(n log n)", "O(W log n)"], 1, "The DP table has n rows and W columns, which is pseudo-polynomial in the value of W."),
        ("With coin denominations {1,3,4} and amount 6, how many coins does a greedy largest-first strategy use?", ["2", "3", "4", "6"], 1, "Greedy takes 4 then 1+1 for 3 coins, while the optimal 3+3 uses only 2."),
        ("Computing the longest common subsequence with two rolling rows of length n+1 uses:", ["O(mn) space", "O(n) space", "O(m+n) space", "O(1) space"], 1, "Only two rows of the DP table are retained instead of the full grid."),
        ("The condition that lets DP beat plain recursion is having:", ["Greedy choice property", "Overlapping subproblems", "Sorted input", "Independent subproblems"], 1, "If subproblems never repeat, simple recursion already suffices."),
        ("The edit distance between 'kitten' and 'sitting' is:", ["2", "3", "4", "5"], 1, "Three operations are needed: k to s, e to i, and inserting g at the end."),
        ("The number of distinct subsequences of a string of length n, including the empty subsequence, is:", ["n + 1", "n!", "2^n", "2^(n-1)"], 2, "Each of the n characters is either taken or skipped, giving 2^n combinations."),
        ("With memoization, how many times is fib(k) computed while evaluating fib(n) for k <= n?", ["Twice", "n times", "2^n times", "Exactly once"], 3, "The cache stores each subproblem's answer on first computation, so later calls reuse it."),
        ("Counting the ways to climb n stairs taking 1 or 2 steps at a time follows:", ["The Fibonacci recurrence", "2^n growth", "n! growth", "A greedy choice"], 0, "ways(n) = ways(n-1) + ways(n-2), which is the Fibonacci recurrence with shifted base cases."),
        ("In the 0/1 knapsack problem, each item may be:", ["Taken an unlimited number of times", "Taken at most once", "Split into fractional pieces", "Taken only when it fills the knapsack exactly"], 1, "0/1 means every item is either included once or excluded, unlike the unbounded or fractional variants."),
    ],
}

IT_LESSONS: dict[str, dict] = {
    "sql-basic-queries": {
        "title": "SQL Basic Queries",
        "notes": "Every SQL query starts with SELECT, then FROM, then optional filtering, sorting and limiting. Think about the logical order of evaluation rather than the order you type: FROM builds the source rows, WHERE filters individual rows, GROUP BY collapses them, HAVING filters the groups, SELECT produces the output columns, ORDER BY sorts the final result and LIMIT truncates it. Knowing this order explains most beginner mistakes.\n- DISTINCT removes duplicate rows from the projected columns. It is a set operation, so it changes how many rows come back, not which columns exist.\n- NULL means unknown, not zero and not an empty string. Any comparison with NULL yields UNKNOWN, so `col = NULL` always returns no rows. Use IS NULL, IS NOT NULL, or COALESCE to substitute a default.\n- COUNT(*) counts rows; COUNT(col) counts non-NULL values of that column; AVG and SUM also ignore NULLs. This is why AVG(10, NULL, 30) is 20.\n- ORDER BY sorts ascending by default. You may sort by an alias defined in SELECT, but you cannot reference that alias in WHERE because WHERE runs first.\n- LIKE uses % for any run of characters and _ for exactly one character. Patterns are case-sensitive depending on collation.\nPractise predicting row counts and column values by hand before running a query; that habit pays off later in joins and window functions.",
        "examples": [
            "Find customers who have no email — SELECT * FROM customers WHERE email IS NULL;",
            "Return the top three earners — SELECT name, salary FROM emp ORDER BY salary DESC LIMIT 3;",
            "Count rows per status without duplicates — SELECT COUNT(DISTINCT status) FROM orders;",
        ],
        "practice": [
            "Write a query that returns names starting with 'A' and containing at least three characters.",
            "Predict the output of SELECT 10 + NULL, COUNT(*) and COUNT(email) on a table with NULL emails.",
            "Explain why ORDER BY salary works with a SELECT alias but WHERE salary_alias > 100 does not.",
        ],
        "code": "SELECT name, department, salary\nFROM employees\nWHERE department = 'Engineering' AND salary IS NOT NULL\nORDER BY salary DESC\nLIMIT 10;",
    },
    "sql-joins": {
        "title": "SQL Joins",
        "notes": "A join combines rows from two tables based on a related column. The join type decides which rows survive.\n- INNER JOIN keeps only rows with a match on both sides.\n- LEFT JOIN keeps every row of the left table; unmatched right columns come back as NULL. RIGHT JOIN is the mirror image.\n- FULL OUTER JOIN keeps unmatched rows from both sides, filling gaps with NULL.\n- CROSS JOIN is the Cartesian product: rows(A) * rows(B).\n- SELF JOIN gives one table two aliases, for example an employee joined to its manager.\nON and WHERE behave differently for outer joins. The ON condition decides matches while the join is being built, so it does not discard unmatched left rows. Putting a right-table predicate in WHERE afterwards removes those NULL-extended rows and silently turns the query into an inner join. If you intend to filter without losing rows, put the condition in ON, or filter the left table in WHERE.\nNULLs never match. Because NULL = NULL is UNKNOWN, rows whose join key is NULL cannot pair with anything, not even another NULL. Coalesce keys or handle them separately if that matters.\nJoins multiply rows when the key is not unique on one side; check the cardinality before trusting aggregates. Multi-table queries chain joins left to right, and each intermediate result can be filtered.",
        "examples": [
            "Customers with their orders — SELECT c.name, o.id FROM customers c LEFT JOIN orders o ON o.cid = c.id;",
            "Find departments without employees — SELECT d.* FROM departments d LEFT JOIN employees e ON e.dept = d.id WHERE e.id IS NULL;",
            "Self join for managers — SELECT e.name, m.name FROM emp e JOIN emp m ON e.manager_id = m.id;",
        ],
        "practice": [
            "Rewrite a LEFT JOIN with WHERE B.col = 'x' so unmatched A rows are preserved.",
            "Write a query returning products that have never been ordered.",
            "Predict the row count of a three-table join where one table has duplicate keys.",
        ],
        "code": "SELECT c.name, COUNT(o.id) AS orders\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.name\nORDER BY orders DESC;",
    },
    "sql-group-by": {
        "title": "SQL GROUP BY and Aggregates",
        "notes": "GROUP BY collapses many rows into summary rows by grouping on one or more key columns. Once you group, every column you SELECT must either be a grouping key or be wrapped in an aggregate such as COUNT, SUM, AVG, MIN, MAX or COUNT(DISTINCT x).\n- WHERE filters rows before grouping, so aggregate functions are not allowed there. HAVING filters groups after they exist, which is why HAVING can contain aggregates.\n- NULLs form their own group. They are ignored by AVG, SUM, MIN and MAX, counted by COUNT(col) only when non-NULL, and always counted by COUNT(*). An aggregate over no non-NULL values returns NULL, not zero, except COUNT which returns 0.\n- GROUP BY does not sort. The database is free to return groups in any order, so always add ORDER BY if presentation matters.\n- COUNT(DISTINCT customer) answers how many different customers, while COUNT(*) answers how many rows.\n- Filtering a single row and filtering a group are different questions: WHERE salary > 5000 keeps individuals, HAVING COUNT(*) > 2 keeps departments.\nA reliable mental model: run WHERE first on raw rows, group the survivors, evaluate HAVING on each group, then project and sort.",
        "examples": [
            "Departments with more than five staff — SELECT dept, COUNT(*) FROM emp GROUP BY dept HAVING COUNT(*) > 5;",
            "Average order value excluding NULL amounts — SELECT AVG(amount) FROM orders;",
            "Distinct product count per category — SELECT category, COUNT(DISTINCT product) FROM items GROUP BY category;",
        ],
        "practice": [
            "Given sales(region, amount), return each region's total and only regions totalling over 1000.",
            "Explain why SELECT dept, AVG(sal) FROM emp WHERE AVG(sal) > 5000 fails and rewrite it.",
            "Predict the number of groups when the grouping column contains three NULLs and two 'A' values.",
        ],
        "code": "SELECT department, COUNT(*) AS headcount, AVG(salary) AS avg_salary\nFROM employees\nWHERE active = 1\nGROUP BY department\nHAVING COUNT(*) > 2\nORDER BY avg_salary DESC;",
    },
    "sql-subqueries": {
        "title": "SQL Subqueries",
        "notes": "A subquery is a query nested inside another. Three shapes cover most uses.\n- Scalar subquery returns exactly one value and can appear anywhere a value is allowed: WHERE salary = (SELECT MAX(salary) FROM emp). More than one row causes an error.\n- Table subquery returns rows and is used with IN, EXISTS, ANY or ALL, or as a derived table in FROM (where it usually needs an alias).\n- Correlated subquery references columns of the outer query, so it is re-evaluated once per outer row. It is powerful but can be slow; think of it as a loop.\nEXISTS tests for non-emptiness and short-circuits on the first matching row, which often beats IN for large sets. `x = ANY (subquery)` is equivalent to `x IN (subquery)`.\nWatch the NULL trap: if a NOT IN subquery returns even one NULL, the whole predicate is never TRUE and the outer query returns nothing. Prefer NOT EXISTS in that situation.\nExecution order matters: a non-correlated inner query runs first and its result feeds the outer query. In a correlated one, the database alternates between outer rows and inner lookups.\nDerived tables in FROM let you compute aggregates first and then join or filter them cleanly.",
        "examples": [
            "Employees earning the company max — SELECT name FROM emp WHERE salary = (SELECT MAX(salary) FROM emp);",
            "Customers who placed no orders — SELECT c.* FROM customers c WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.cid = c.cid);",
            "Products above average price — SELECT p.* FROM products p JOIN (SELECT AVG(price) a FROM products) x ON p.price > x.a;",
        ],
        "practice": [
            "Rewrite a NOT IN query that returns zero rows because the subquery contains NULL.",
            "Rewrite a correlated EXISTS query as an inner join and compare results.",
            "Write a scalar subquery returning the second-highest salary.",
        ],
        "code": "SELECT name\nFROM employees e\nWHERE salary > (SELECT AVG(salary) FROM employees)\n  AND EXISTS (SELECT 1 FROM reviews r WHERE r.emp_id = e.id);",
    },
    "sql-window-functions": {
        "title": "SQL Window Functions",
        "notes": "A window function computes across a set of rows related to the current row without collapsing them, unlike GROUP BY. The syntax is function() OVER (PARTITION BY ... ORDER BY ... frame).\n- PARTITION BY splits the result into independent windows; ORDER BY orders rows inside each window.\n- The frame clause controls which rows are included. With ORDER BY present the default frame is ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW, which produces a running total. With no ORDER BY, the default is the whole partition, so SUM(x) OVER (PARTITION BY g) repeats the group total on every row.\n- Ranking: ROW_NUMBER gives unique consecutive numbers, RANK leaves gaps after ties, DENSE_RANK never gaps, NTILE(n) splits rows into n buckets.\n- LAG and LEAD read neighbouring rows, useful for period-over-period deltas; FIRST_VALUE and LAST_VALUE read frame edges.\n- Window functions are evaluated after WHERE and GROUP BY, so you cannot filter on them directly. Wrap the query in a CTE or subquery, or use QUALIFY where supported.\nWindows are ideal for running totals, moving averages, top-N-per-group and deduplication.",
        "examples": [
            "Running total per customer — SELECT cid, amt, SUM(amt) OVER (PARTITION BY cid ORDER BY day) FROM sales;",
            "Rank products by revenue — SELECT p, rev, RANK() OVER (ORDER BY rev DESC) FROM products;",
            "Day-over-day change — SELECT day, amt, amt - LAG(amt) OVER (ORDER BY day) FROM sales;",
        ],
        "practice": [
            "Write ROW_NUMBER() OVER (PARTITION BY dept ORDER BY salary DESC) to keep only the top earner per department.",
            "Explain how the default frame changes when you remove ORDER BY from the OVER clause.",
            "Compute a 3-row moving average with an explicit frame clause.",
        ],
        "code": "SELECT name, department, salary,\n       RANK() OVER (PARTITION BY department ORDER BY salary DESC) AS rnk,\n       SUM(salary) OVER (ORDER BY salary DESC ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS running\nFROM employees;",
    },
    "dsa-arrays": {
        "title": "DSA Arrays",
        "notes": "An array stores elements in contiguous memory, so element i is found at base + i * size. That gives O(1) random access by index and excellent cache locality, which is why arrays beat linked lists for traversal in practice.\n- Reading and updating by index: O(1). Scanning: O(n). Binary search on sorted data: O(log n).\n- Inserting or deleting in the middle costs O(n) because the remaining elements must shift.\n- Dynamic arrays (Python list, ArrayList) grow automatically. Appends are O(1) amortized: capacity roughly doubles on resize, and the rare copy cost averages out over many appends. Inserting at the front is still worst-case O(n).\n- Space is O(n); a growth factor leaves at most a constant-factor over-allocation.\nTwo workhorse patterns come from arrays:\n- Two pointers walk inward or chase each other for pair sums, palindrome checks and in-place partitioning.\n- Sliding window maintains a contiguous segment with a valid property, turning nested loops into a single O(n) pass.\nKadane's algorithm is the classic one-pass DP: track the best sum ending here, reset when it turns negative.",
        "examples": [
            "Two sum with a hash set — for each x, if target - x seen, return pair; else store x.",
            "Maximum subarray — best = max(a[i], best + a[i]); answer = max(answer, best).",
            "Remove duplicates in place — slow pointer writes only when arr[slow] != arr[fast].",
        ],
        "practice": [
            "Given a sorted array, rotate it and then search for a target in better than O(n).",
            "Implement an in-place move of all zeros to the end while keeping order.",
            "Compute the maximum sum of a non-adjacent subsequence in O(n) time and O(1) space.",
        ],
        "code": "def max_subarray(a):\n    best = cur = a[0]\n    for x in a[1:]:\n        cur = max(x, cur + x)\n        best = max(best, cur)\n    return best",
    },
    "dsa-strings": {
        "title": "DSA Strings",
        "notes": "A string is an array of characters, so most string algorithms reuse array ideas, but immutability changes the cost model. In Python and Java, strings cannot be modified: every concatenation allocates a new object, so `s += part` in a loop is O(n^2). Build a list of parts and call join once.\n- Scanning a string once for vowels, digits or case is O(n) time and O(1) or O(alphabet) space.\n- Palindrome checks use two pointers from both ends, O(n) time and O(1) space; skip non-alphanumeric characters for real-world input.\n- Anagram tests compare character frequency maps: O(n) time with a fixed-size array of 26 counters, or sort both strings for O(n log n).\n- Substrings are contiguous; subsequences preserve order but may skip characters. That distinction drives LCS and edit distance.\n- For pattern matching, the naive search is O(n*m). KMP precomputes a failure function so the pointer never rewinds, giving O(n+m). Rolling hashes give the same bound on average.\n- The longest substring without repeating characters uses a sliding window plus a map of last-seen indices.",
        "examples": [
            "Validate a palindrome — two pointers i and j, advance while s[i] is non-alphanumeric.",
            "Group anagrams — key each word by ''.join(sorted(word)), bucket words by that key.",
            "First unique character — one pass records counts, a second pass finds the first count of one.",
        ],
        "practice": [
            "Find the length of the longest substring with all distinct characters in O(n).",
            "Reverse the order of words in a sentence without splitting built-ins.",
            "Check whether one string is a rotation of another using a doubled-string trick.",
        ],
        "code": "def is_palindrome(s):\n    i, j = 0, len(s) - 1\n    while i < j:\n        if s[i] != s[j]:\n            return False\n        i += 1\n        j -= 1\n    return True",
    },
    "dsa-linked-lists": {
        "title": "DSA Linked Lists",
        "notes": "A linked list stores nodes, each holding a value and a reference to the next node; a doubly linked list also keeps a prev reference. Memory is not contiguous, so there is no index arithmetic and no shifting.\n- Insert at head: O(1). Insert at tail without a tail pointer: O(n); with one: O(1). Delete a known node: O(1) in a doubly linked list (re-link neighbours), but O(n) in a singly linked list because you must reach the node's predecessor.\n- Search and indexing are O(n); there is no random access, which is the main disadvantage versus arrays.\n- Space per node includes an extra pointer, so linked lists use more memory per element and suffer poor cache locality.\nKey techniques:\n- Fast and slow pointers find the middle, detect a cycle (Floyd's algorithm, O(n) time and O(1) space) and find cycle entry points.\n- Reversing uses three pointers prev, curr, next in a loop: O(n) time, O(1) space. The recursive version is O(n) stack space.\n- Dummy head nodes eliminate special cases when inserting or deleting at position zero.\nChoose a linked list when you mostly insert and delete at known positions and rarely index by position.",
        "examples": [
            "Reverse a list — prev = None; while cur: nxt = cur.next; cur.next = prev; prev = cur; cur = nxt.",
            "Detect a cycle — slow moves 1 step, fast moves 2; if they meet, a cycle exists.",
            "Merge two sorted lists — repeatedly attach the smaller head and advance that pointer.",
        ],
        "practice": [
            "Remove the n-th node from the end in one pass using two pointers with an n gap.",
            "Find the start node of a cycle without using extra memory.",
            "Flatten a linked list whose nodes carry a second 'random' pointer.",
        ],
        "code": "def reverse(head):\n    prev = None\n    cur = head\n    while cur:\n        nxt = cur.next\n        cur.next = prev\n        prev = cur\n        cur = nxt\n    return prev",
    },
    "dsa-stacks": {
        "title": "DSA Stacks",
        "notes": "A stack is a last-in-first-out collection with two core operations: push adds to the top, pop removes from the top. peek or top reads without removing. Both are O(1) whether implemented with a dynamic array (append and pop at the end) or a singly linked list that keeps the head as the top.\nWhy LIFO matters: many problems involve nesting or going back to the most recent unfinished work.\n- Bracket matching: push opening brackets, pop on closers and demand a match; empty stack at the end means valid.\n- Postfix evaluation: push operands, pop two values per operator, push the result.\n- Expression conversion between infix and postfix uses an operator stack ordered by precedence and associativity.\n- DFS, whether of a graph or a tree, is the stack algorithm; recursion is just the call stack doing it for you.\n- Undo history, browser back buttons, function call frames and syntax parsing are all stacks.\nAdvanced pattern: a monotonic stack keeps elements in sorted order and solves next-greater-element and largest-rectangle-in-histogram problems in O(n).\nA fixed-capacity array stack risks overflow; a linked stack pays pointer overhead but never needs resizing.",
        "examples": [
            "Valid parentheses — push '(' and require pop() == '(' for every ')'.",
            "Evaluate postfix — for token in expr: operand ? push : push(pop() op pop()).",
            "Next greater element — pop indices whose value is smaller than the current value.",
        ],
        "practice": [
            "Convert an infix expression with parentheses to postfix notation.",
            "Implement a stack that returns the minimum element in O(1) using O(n) extra space.",
            "Use a stack to check whether an HTML document has correctly nested tags.",
        ],
        "code": "class Stack:\n    def __init__(self):\n        self.data = []\n    def push(self, x):\n        self.data.append(x)\n    def pop(self):\n        return self.data.pop()\n    def top(self):\n        return self.data[-1]",
    },
    "dsa-queues": {
        "title": "DSA Queues",
        "notes": "A queue is first-in-first-out: enqueue adds at the rear, dequeue removes from the front, and both are O(1) when front and rear are tracked properly.\nNaive array implementations shift elements on every dequeue and become O(n). Two standard fixes:\n- Circular queue: head and tail indices wrap around the array, reusing freed slots in O(1).\n- Linked queue with head and tail pointers: constant-time operations with no wasted capacity, at the cost of per-node pointers.\nWhere queues appear:\n- BFS explores a graph or tree level by level; the queue guarantees the shortest path in an unweighted graph.\n- Round-robin scheduling and printer spooling re-enqueue jobs that are not finished.\n- Sliding window problems use a deque (double-ended queue). A monotonic deque solves sliding window maximum in O(n) by keeping candidate indices in decreasing order.\n- Implementing a stack with two queues, or a queue with two stacks, is a classic interview exercise; the two-stack queue gives O(1) amortized per operation by swapping the stacks when the front stack empties.\nKnow the difference: stack for depth and nesting, queue for breadth and fairness.",
        "examples": [
            "Level order traversal — enqueue root, dequeue node, print it, enqueue its children.",
            "Sliding window maximum — drop front indices outside the window, drop rear values smaller than the new one.",
            "Queue with two stacks — push to in-stack, transfer to out-stack only when out-stack is empty.",
        ],
        "practice": [
            "Implement a circular queue of fixed capacity with overflow and underflow checks.",
            "Compute the first negative integer in every window of size k using a queue.",
            "Explain why BFS finds the shortest unweighted path while DFS does not.",
        ],
        "code": "from collections import deque\n\ndef bfs(graph, start):\n    seen = {start}\n    q = deque([start])\n    while q:\n        node = q.popleft()\n        for nb in graph[node]:\n            if nb not in seen:\n                seen.add(nb)\n                q.append(nb)\n    return seen",
    },
    "dsa-trees": {
        "title": "DSA Trees",
        "notes": "A tree is a connected acyclic graph with n nodes and exactly n-1 edges. A node's degree is its number of children; depth is the distance from the root and height is the longest downward path (the root alone has height 0 or 1 depending on convention).\nBinary tree: at most two children. Full (every node has 0 or 2), complete (all levels filled except possibly the last, filled left to right), perfect (all internal nodes have two children and all leaves share one depth), and balanced (left and right subtree heights differ by at most one).\nBinary search tree: left subtree keys < root < right subtree keys. Inorder traversal therefore yields keys in ascending order. Search, insert and delete are O(h); when balanced, h = O(log n), but a sorted insertion sequence degenerates to a linked list and O(n).\nTraversals:\n- Preorder root-left-right, useful for copying trees.\n- Inorder left-root-right, sorted output for BSTs.\n- Postorder left-right-root, used for deletion and directory size calculations.\n- Level order uses a queue, O(n) time and O(width) space.\nArrays represent complete binary trees compactly: children of index i are 2i+1 and 2i+2, parents are floor((i-1)/2), which is how heaps work.",
        "examples": [
            "Inorder iteratively — push left children, pop and visit, then go right.",
            "Maximum depth — 1 + max(depth(left), depth(right)), 0 for an empty tree.",
            "Validate a BST — pass (low, high) bounds down and check each key lies inside.",
        ],
        "practice": [
            "Serialize and deserialize a binary tree so structure survives a round trip.",
            "Convert a sorted array into a height-balanced BST in O(n).",
            "Compute the width of a tree's widest level using level-order traversal.",
        ],
        "code": "def inorder(root):\n    out, stack, cur = [], [], root\n    while cur or stack:\n        while cur:\n            stack.append(cur)\n            cur = cur.left\n        cur = stack.pop()\n        out.append(cur.val)\n        cur = cur.right\n    return out",
    },
    "dsa-graphs": {
        "title": "DSA Graphs",
        "notes": "A graph is vertices plus edges, directed or undirected, possibly weighted. Choose a representation deliberately:\n- Adjacency list: O(V+E) space, ideal for sparse graphs, and iteration over neighbours is proportional to degree.\n- Adjacency matrix: O(V^2) space, O(1) edge lookup, best for dense graphs.\n- Edge list: simple, but neighbour lookups need a scan or a sort.\nTraversals both run in O(V+E) with an adjacency list and O(V^2) with a matrix:\n- BFS uses a queue, explores level by level, and gives shortest paths in unweighted graphs.\n- DFS uses a stack or recursion, explores deep paths first, and is the basis for cycle detection, topological sort and connected components.\nCycle detection differs by graph type: in undirected DFS you must remember the parent; in directed graphs track three colours (unvisited, in-stack, done) and a back edge signals a cycle.\nClassic algorithms:\n- Dijkstra with a priority queue for non-negative single-source shortest paths.\n- Bellman-Ford handles negative weights and detects negative cycles in O(V*E).\n- Floyd-Warshall computes all pairs in O(V^3).\n- Topological sort (Kahn's BFS or DFS) only exists for DAGs.\n- Prim and Kruskal both build a minimum spanning tree with V-1 edges.\n- Bipartiteness is a two-colouring check via BFS or DFS.",
        "examples": [
            "Connected components — run DFS from every unvisited vertex and count restarts.",
            "Shortest path in an unweighted grid — BFS with distance tracking from the source.",
            "Topological order — Kahn's algorithm repeatedly removes vertices with in-degree zero.",
        ],
        "practice": [
            "Detect whether a directed graph contains a cycle using iterative DFS and three colours.",
            "Find the number of islands in a grid of land and water cells.",
            "Implement Dijkstra and reconstruct the path, not only the distance.",
        ],
        "code": "def topo_sort(graph, indeg):\n    from collections import deque\n    q = deque(v for v in graph if indeg[v] == 0)\n    order = []\n    while q:\n        u = q.popleft()\n        order.append(u)\n        for v in graph[u]:\n            indeg[v] -= 1\n            if indeg[v] == 0:\n                q.append(v)\n    return order",
    },
    "dsa-dp": {
        "title": "DSA Dynamic Programming",
        "notes": "Dynamic programming applies when a problem has two properties: optimal substructure (the best answer is built from best answers to smaller instances) and overlapping subproblems (brute-force recursion keeps solving the same instance again and again).\nTwo ways to implement it:\n- Top-down memoization: write the natural recursion, cache results in a dict or array. Easy to derive, but uses recursion stack space.\n- Bottom-up tabulation: fill a table from base cases upward. Usually faster and free of stack-depth risk.\nSteps: define the state clearly (what does dp[i] or dp[i][j] mean?), write the recurrence, set base cases, and decide the iteration order so dependencies are ready first.\nClassic results:\n- Fibonacci: O(n) time with memo, O(n) or O(1) space iteratively.\n- 0/1 knapsack: dp[i][w] using the first i items with capacity w, O(nW) time, which is pseudo-polynomial because W is a numeric value.\n- Longest common subsequence: O(mn) time, reducible to O(min(m,n)) space with rolling rows.\n- Edit distance: O(mn) with three-way transition (insert, delete, replace).\n- Coin change: greedy largest-first fails for sets like {1,3,4} and amount 6 (greedy 3 coins, optimal 3+3 = 2), so DP is required.\nOptimize space whenever the recurrence only references the previous row.",
        "examples": [
            "Coin change — dp[0] = 0, dp[x] = 1 + min(dp[x - c]) over coins c, else infinity.",
            "LCS length — match: dp[i-1][j-1] + 1; else max(dp[i-1][j], dp[i][j-1]).",
            "Climbing stairs — dp[i] = dp[i-1] + dp[i-2], the Fibonacci recurrence in disguise.",
        ],
        "practice": [
            "Solve subset sum using a 1-D boolean DP array and explain the iteration direction.",
            "Compute the minimum cost to climb stairs with a per-step cost.",
            "Reduce LCS space from O(mn) to O(n) and justify why it still works.",
        ],
        "code": "def coin_change(coins, amount):\n    INF = amount + 1\n    dp = [0] + [INF] * amount\n    for x in range(1, amount + 1):\n        for c in coins:\n            if c <= x:\n                dp[x] = min(dp[x], dp[x - c] + 1)\n    return -1 if dp[amount] > amount else dp[amount]",
    },
}


def get_it(slug: str) -> list[dict]:
    return [
        {"question_text": q, "options": list(opts), "correct_index": idx, "explanation": expl, "difficulty": "beginner"}
        for q, opts, idx, expl in IT_BANKS[slug]
    ]
